library(tidyverse)
library(tidylog)

source("code/functions.R")

jail_prison_list <-
  arrow::read_feather("data/jails_prisons.feather") |>
  distinct(name, state) |>
  mutate(name_join = clean_text(name))

# select places that are not
facilities_from_detentions <-
  arrow::read_feather(
    "data/facilities-from-detentions.feather"
  ) |>
  mutate(name_join = clean_text(detention_facility)) |>
  filter(!str_detect(name_join, "hosp|\\bmed\\b|health|clinic|emerg")) |>
  select(detention_facility_code, name = detention_facility, name_join) |>
  filter(!str_detect(detention_facility_code, "^BOP")) |>
  mutate(
    state = str_sub(detention_facility_code, -2),
    # state = case_when(
    #   !state_guess %in% c(state.abb, "PR") |
    #     str_sub(detention_facility_code, 1, 2) %in% c(state.abb, "PR") |
    #     str_sub(detention_facility_code, 1, 3) == "BOP" |
    #     nchar(detention_facility_code) < 7 ~ NA_character_,
    #   TRUE ~ state_guess
    # )
  )

# library(fuzzylink)

# matches_cleaned <-
#   fuzzylink::fuzzylink(
#     facilities_from_detentions,
#     jail_prison_list,
#     record_type = "names of detention centers, jails, and prisons",
#     model = "gpt-3.5-turbo-instruct",
#     learner = "ranger",
#     instructions = "compare names of immigration detention facilities to a list of jails and prisons to find possible matches",
#     by = "name_join",
#     blocking.variables = "state",
#     max_labels = 50000,
#     openai_api_key = "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"
#   )

# write_rds(matches_cleaned, file = "~/downloads/matches-jails-prisons.rds")

# matches_cleaned |>
#   as_tibble() |>
#   filter(match == "Yes", match_probability >= 0.75) |>
#   select(name.x, name.y, state) |>
#   arrange(state, name.x) |>
#   clipr::write_clip()

matches_to_check <-
  tribble(
    ~name.x                              , ~name.y                                                   , ~state ,
    "KODIAK CITY JAIL"                   , "Kodiak City Jail"                                        , "AK"   ,
    "BALDWIN COUNTY COR. CENTER"         , "Baldwin County Correctional Center"                      , "AL"   ,
    "DEKALB COUNTY DETENTION CENTER"     , "DeKalb County Detention Center"                          , "AL"   ,
    "ESCAMBIA COUNTY DETENTION CENTER"   , "Escambia County Detention Center"                        , "AL"   ,
    "MONTGOMERY CITY JAIL"               , "Montgomery Municipal Jail"                               , "AL"   ,
    "MONTGOMERY CITY JAIL"               , "Montgomery Municipal Jail"                               , "AL"   ,
    "PICKENS COUNTY DET CTR"             , "Pickens County Jail"                                     , "AL"   ,
    "BENTON COUNTY DETENTION CENTER"     , "Benton County Detention Facility"                        , "AR"   ,
    "FAULKNER COUNTY JAIL"               , "Faulkner County Detention Center Unit 2"                 , "AR"   ,
    "LONOKE COUNTY DET. CENTER"          , "Lonoke County Detention Center"                          , "AR"   ,
    "MILLER COUNTY JAIL"                 , "Miller County Jail"                                      , "AR"   ,
    "PULASKI COUNTY REG.DET.FAC."        , "Pulaski County Regional Detention Facility"              , "AR"   ,
    "SEBASTIAN COUNTY DET CNT"           , "Sebastian County Adult Detention Center"                 , "AR"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Detention Center"                      , "AR"   ,
    "COCONINO CO DETENTION FACILITY"     , "Coconino County Jail"                                    , "AZ"   ,
    "GILA COUNTY JAIL"                   , "Gila County Globe Jail"                                  , "AZ"   ,
    "MARICOPA COUNTY JAIL"               , "Maricopa County Estrella Jail"                           , "AZ"   ,
    "MARICOPA COUNTY JAIL"               , "Maricopa County Durango Jail"                            , "AZ"   ,
    "MARICOPA COUNTY JAIL"               , "Maricopa County Lower Buckeye Jail"                      , "AZ"   ,
    "MARICOPA COUNTY JAIL"               , "Maricopa County Fourth Avenue Jail"                      , "AZ"   ,
    "NAVAJO COUNTY SHERIFF"              , "Navajo County Detention Center"                          , "AZ"   ,
    "PIMA COUNTY JAIL"                   , "Pima County Adult Detention Complex"                     , "AZ"   ,
    "PINAL COUNTY JAIL"                  , "Pinal County Jail"                                       , "AZ"   ,
    "SANTA CRUZ CO JAIL AZ"              , "Santa Cruz County Adult Detention Center"                , "AZ"   ,
    "YAVAPAI COUNTY DETENTION CENTER"    , "Yavapai County Camp Verde Facility"                      , "AZ"   ,
    "YUMA COUNTY JUVENILE CENT"          , "Yuma County Detention Center"                            , "AZ"   ,
    "FRESNO COUNTY JAIL"                 , "Fresno County Jail"                                      , "CA"   ,
    "GLENN COUNTY JAIL"                  , "Glenn County Jail"                                       , "CA"   ,
    "KERN COUNTY JAIL (LERDO)"           , "Kern County Lerdo Pre-Trial Facility"                    , "CA"   ,
    "KERN COUNTY JAIL (LERDO)"           , "Kern County Lerdo Maximum-Medium"                        , "CA"   ,
    "KERN COUNTY JAIL (LERDO)"           , "Kern County Lerdo Justice Facility"                      , "CA"   ,
    "LOS ANGELES COUNTY JAIL-TWIN TOWER" , "Los Angeles County - Twin Towers Correctional Facility"  , "CA"   ,
    "MARIN CO. JAIL"                     , "Marin County Jail"                                       , "CA"   ,
    "MERCED COUNTY JAIL"                 , "MercedCountyJail"                                        , "CA"   ,
    "ORANGE COUNT INTAKE RELEASE FAC."   , "Orange County Jails - Intake/Release Center"             , "CA"   ,
    "SAN BERNARDINO CO. JAIL"            , "San Bernardino County W. Valley Detention Center"        , "CA"   ,
    "SAN BERNARDINO CO. JAIL"            , "San Bernardino County Central Detention Center"          , "CA"   ,
    "SAN DIEGO COUNTY JAIL"              , "San Diego County Detention Facility 8"                   , "CA"   ,
    "SAN DIEGO COUNTY JUV.HALL"          , "San Diego Jail"                                          , "CA"   ,
    "SAN DIEGO COUNTY JUV.HALL"          , "San Diego County Detention Facility 8"                   , "CA"   ,
    "SAN FRANCISCO CO JAIL"              , "San Francisco Jail #4"                                   , "CA"   ,
    "SAN JOAQUIN COUNTY JAIL"            , "San Joaquin County Jail"                                 , "CA"   ,
    "SAN LUIS OBISPO CO JAIL"            , "San Luis Obispo County Jail"                             , "CA"   ,
    "SAN LUIS OBISPO CO. JUVEN"          , "San Luis Obispo County Jail"                             , "CA"   ,
    "SAN MATEO CO JAIL"                  , "San Mateo County Maguire Correctional Facility"          , "CA"   ,
    "SANTA BARBARA COUNTY JAIL"          , "Santa Barbara County Jails"                              , "CA"   ,
    "SANTA CLARA CO JAIL/ELMWOOD"        , "Santa Clara County Jail"                                 , "CA"   ,
    "SANTA CLARA COUNTY JAIL"            , "Santa Clara County Jail"                                 , "CA"   ,
    "SANTA CRUZ CO MAIN JAIL"            , "Santa Cruz County Main Jail and Womens Facility"         , "CA"   ,
    "SONOMA CO MAIN ADULT DET"           , "Sonoma County Main Adult Detention Facility"             , "CA"   ,
    "TEHAMA COUNTY JAIL"                 , "Tehama County Jail"                                      , "CA"   ,
    "TULARE COUNTY JAIL"                 , "Tulare County Main Jail"                                 , "CA"   ,
    "VENTURA COUNTY JAIL"                , "Ventura County Jail - Todd Road"                         , "CA"   ,
    "VENTURA COUNTY JAIL"                , "Ventura County East Valley Jail"                         , "CA"   ,
    "YUBA COUNTY JAIL"                   , "Yuba County Jail"                                        , "CA"   ,
    "ARAPAHOE COUNTY JAIL"               , "Arapahoe County Sheriffs Office Detention Facility"      , "CO"   ,
    "BENT COUNTY JAIL"                   , "Bent County Jail"                                        , "CO"   ,
    "BOULDER COUNTY JAIL"                , "Boulder County Jail"                                     , "CO"   ,
    "BROOMFIELD DETENTION CENTER"        , "Broomfield Detention Center"                             , "CO"   ,
    "CHAFFEE COUNTY JAIL"                , "Chaffee County Jail"                                     , "CO"   ,
    "CLEAR CREEK COUNTY JAIL"            , "Clear Creek County Jail"                                 , "CO"   ,
    "CONEJOS COUNTY JAIL"                , "Conejos County Jail"                                     , "CO"   ,
    "COSTILLA COUNTY JAIL"               , "Costilla County Jail"                                    , "CO"   ,
    "DELTA COUNTY JAIL"                  , "Delta County Jail"                                       , "CO"   ,
    "DENVER COUNTY JAIL"                 , "Denver County Jail"                                      , "CO"   ,
    "DENVER COUNTY JAIL"                 , "Denver Downtown Detention Center"                        , "CO"   ,
    "DOUGLAS COUNTY DETENTION CENTER"    , "Douglas County Detention Facility"                       , "CO"   ,
    "DOUGLAS COUNTY DETENTION FACILITY"  , "Douglas County Detention Facility"                       , "CO"   ,
    "EAGLE COUNTY JAIL"                  , "Eagle County Correctional Facility"                      , "CO"   ,
    "EL PASO COUNTY JAIL (CO)"           , "El Paso County Criminal Justice Center"                  , "CO"   ,
    "ELBERT COUNTY JAIL"                 , "Elbert County Jail"                                      , "CO"   ,
    "GARFIELD COUNTY JAIL"               , "GarfieldCounty Jail"                                     , "CO"   ,
    "GILPIN COUNTY SHERIFF"              , "Gilpin County Jail"                                      , "CO"   ,
    "GRAND COUNTY JAIL"                  , "Grand County Jail"                                       , "CO"   ,
    "GUNNISON COUNTY JAIL"               , "Gunnison County Jail"                                    , "CO"   ,
    "HUERFANO COUNTY JAIL"               , "Huerfano County Jail"                                    , "CO"   ,
    "JEFFERSON COUNTY JAIL"              , "Jefferson County Jail"                                   , "CO"   ,
    "LA PLATA COUNTY JAIL"               , "La Plata County Jail"                                    , "CO"   ,
    "LAKE COUNTY JAIL"                   , "Lake County Jail"                                        , "CO"   ,
    "LARIMER COUNTY JAIL"                , "Larimer County Jail"                                     , "CO"   ,
    "LINCOLN COUNTY JAIL"                , "Lincoln County Jail"                                     , "CO"   ,
    "MOFFAT COUNTY JAIL"                 , "Moffat County Jail"                                      , "CO"   ,
    "MONTEZUMA COUNTY JAIL"              , "Montezuma County Jail"                                   , "CO"   ,
    "MONTROSE COUNTY JAIL"               , "Montrose County Jail"                                    , "CO"   ,
    "OTERO COUNTY JAIL"                  , "Otero County Jail"                                       , "CO"   ,
    "PARK COUNTY JAIL"                   , "Park County Jail"                                        , "CO"   ,
    "PITKIN COUNTY JAIL"                 , "Pitkin County Jail"                                      , "CO"   ,
    "PROWERS COUNTY JAIL"                , "Prowers County Jail"                                     , "CO"   ,
    "RIO BLANCO COUNTY JAIL"             , "Rio Blanco County Jail"                                  , "CO"   ,
    "RIO GRANDE COUNTY JAIL"             , "Rio Grande County Jail"                                  , "CO"   ,
    "ROUTT COUNTY JAIL"                  , "Routt County Jail"                                       , "CO"   ,
    "SAGUACHE COUNTY JAIL"               , "Saguache County Jail"                                    , "CO"   ,
    "SAN MIGUEL COUNTY JAIL"             , "San Miguel County Jail"                                  , "CO"   ,
    "SUMMIT COUNTY JAIL"                 , "Summit County Jail"                                      , "CO"   ,
    "TELLER COUNTY JAIL"                 , "Teller County Jail"                                      , "CO"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Jail"                                  , "CO"   ,
    "WELD COUNTY JAIL"                   , "Weld County Jail"                                        , "CO"   ,
    "YUMA COUNTY JAIL"                   , "Yuma County Jail"                                        , "CO"   ,
    "BAKER COUNTY SHERIFF DEPT."         , "Baker County Detention Center"                           , "FL"   ,
    "BAY COUNTY"                         , "Bay County Jail Facility"                                , "FL"   ,
    "BRADFORD COUNTY JAIL"               , "Bradford County Jail"                                    , "FL"   ,
    "BREVARD COUNTY JAIL COMPLEX"        , "Brevard County Jail"                                     , "FL"   ,
    "BROWARD CORRECTIONAL"               , "Broward County Main Jail"                                , "FL"   ,
    "BROWARD COUNTY JAIL"                , "Broward County Main Jail"                                , "FL"   ,
    "CHARLOTTE COUNTY JAIL"              , "Charlotte County Jail"                                   , "FL"   ,
    "CITRUS COUNTY JAIL"                 , "Citrus County Detention Facility - CCA"                  , "FL"   ,
    "CLAY COUNTY JAIL"                   , "Clay County Jail"                                        , "FL"   ,
    "COLLIER COUNTY SHERIFF"             , "Collier County Immokalee Jail Center"                    , "FL"   ,
    "FLAGLER COUNTY JAIL"                , "Flagler County - Inmate Facility"                        , "FL"   ,
    "GLADES COUNTY DETENTION CENTER"     , "Glades CountyJail"                                       , "FL"   ,
    "HENDRY COUNTY JAIL"                 , "Hendry County Jail"                                      , "FL"   ,
    "HERNANDO COUNTY JAIL"               , "Hernando County Detention Center"                        , "FL"   ,
    "INDIAN RIVER COUNTY JAIL"           , "Indian River CountyJail"                                 , "FL"   ,
    "LAKE COUNTY JAIL"                   , "Lake County Jail"                                        , "FL"   ,
    "MARION COUNTY JAIL"                 , "Marion County Jail"                                      , "FL"   ,
    "OSCEOLA COUNTY JAIL"                , "Osceola County Corrections Department"                   , "FL"   ,
    "PALM BEACH COUNTY JAIL"             , "Palm Beach County West Detention Center"                 , "FL"   ,
    "PINELLAS COUNTY JAIL"               , "Pinellas County Jail"                                    , "FL"   ,
    "PUTNAM COUNTY JAIL"                 , "Putnam CountyJail"                                       , "FL"   ,
    "SANTA ROSA COUNTY JAIL"             , "Santa Rosa CountyJail"                                   , "FL"   ,
    "SARASOTA COUNTY JAIL"               , "Sarasota County Jail"                                    , "FL"   ,
    "ST. LUCIE COUNTY JAIL"              , "St. Lucie County Jail"                                   , "FL"   ,
    "SUWANNEE COUNTY JAIL"               , "Suwanee CountyJail"                                      , "FL"   ,
    "TURNER GUIFORD KNIGHT (TGK) JAIL"   , "Turner Guilford Knight Correctional Center"              , "FL"   ,
    "WALTON COUNTY D.O.C."               , "Walton CountyJail"                                       , "FL"   ,
    "WALTON COUNTY JAIL"                 , "Walton CountyJail"                                       , "FL"   ,
    "BARTOW CO JAIL"                     , "Bartow CountyDetention Facility"                         , "GA"   ,
    "CHATHAM CO JAIL"                    , "Chatham County Adult Detention Center"                   , "GA"   ,
    "CHEROKEE CO JAIL GA"                , "Cherokee CountyJail"                                     , "GA"   ,
    "COBB CO SHERIFFS OFC ADULT DET CTR" , "Cobb County Sheriffs Office Jail & Prison Unit"          , "GA"   ,
    "COLQUITT COUNTY JAIL"               , "Colquitt County Jail"                                    , "GA"   ,
    "FLOYD COUNTY JAIL"                  , "Floyd County Jail"                                       , "GA"   ,
    "GWINNETT COUNTY JAIL"               , "Gwinnett County Jail"                                    , "GA"   ,
    "HARRIS COUNTY JAIL"                 , "Harris County Jail"                                      , "GA"   ,
    "IRWIN COUNTY DETENTION CENTER"      , "Irwin County Detention Center"                           , "GA"   ,
    "LINCOLN COUNTY JAIL"                , "Lincoln County Jail"                                     , "GA"   ,
    "MCINTOSH COUNTY JAIL"               , "McIntosh County Jail"                                    , "GA"   ,
    "WALKER COUNTY JAIL"                 , "Walker County Jail"                                      , "GA"   ,
    "WHITFIELD COUNTY JAIL"              , "Whitfield County Jail"                                   , "GA"   ,
    "BLACK HAWK CO JAIL"                 , "Black Hawk County Jail"                                  , "IA"   ,
    "BREMER CO JAIL, IOWA"               , "Bremer County Jail"                                      , "IA"   ,
    "BUENA VISTA CO JAIL"                , "Buena Vista County Jail"                                 , "IA"   ,
    "BUTLER CO JAIL, IOWA"               , "Butler County Jail"                                      , "IA"   ,
    "CARROL COUNTY JAIL"                 , "Carroll County Jail"                                     , "IA"   ,
    "CERRO GORDO COUNTY"                 , "Cerro Gordo County Law Enforcement Center"               , "IA"   ,
    "CLARKE CO SHERIFF"                  , "Clarke County Jail"                                      , "IA"   ,
    "CRAWFORD COUNTY JAIL"               , "Crawford County Jail"                                    , "IA"   ,
    "DALLAS COUNTY SHERIFF'S OFFICE"     , "Dallas County Correctional Facility"                     , "IA"   ,
    "DES MOINES COUNTY JAIL"             , "Des Moines County Jail"                                  , "IA"   ,
    "DICKINSON COUNTY JAIL"              , "Dickinson County Jail"                                   , "IA"   ,
    "EMMET COUNTY JAIL"                  , "Emmet County Jail"                                       , "IA"   ,
    "FREMONT COUNTY SHERIFF"             , "Fremont County Jail"                                     , "IA"   ,
    "GREENE COUNTY JAIL"                 , "Greene County Jail"                                      , "IA"   ,
    "HARDIN CO JAIL"                     , "Hardin County Jail"                                      , "IA"   ,
    "HARRISON COUNTY JAIL"               , "Harrison County Jail"                                    , "IA"   ,
    "HUMBOLDT CO JAIL"                   , "Humboldt County Jail"                                    , "IA"   ,
    "IDA COUNTY JAIL"                    , "Ida County Jail"                                         , "IA"   ,
    "JASPER CO JAIL"                     , "Jasper County Jail"                                      , "IA"   ,
    "JOHNSON COUNTY JAIL"                , "Johnson County Jail"                                     , "IA"   ,
    "KOSSUTH COUNTY JAIL"                , "Kossuth County Jail"                                     , "IA"   ,
    "LOUISA COUNTY JAIL"                 , "Louisa County Jail"                                      , "IA"   ,
    "LYON COUNTY JAIL"                   , "Lyon County Jail"                                        , "IA"   ,
    "MADISON COUNTY JAIL"                , "Madison County Jail"                                     , "IA"   ,
    "MARION COUNTY JAIL"                 , "Marion County Jail"                                      , "IA"   ,
    "MARSHALL COUNTY JAIL"               , "Marshall County Jail"                                    , "IA"   ,
    "MONTGOMERY COUNTY JAIL"             , "Montgomery County Jail"                                  , "IA"   ,
    "MUSCATINE COUNTY JAIL"              , "Muscatine County Jail"                                   , "IA"   ,
    "OBRIEN CO JAIL, IOWA"               , "OBrien County Jail"                                      , "IA"   ,
    "OSCEOLA CO JAIL"                    , "Osceola County Jail"                                     , "IA"   ,
    "PAGE COUNTY JAIL"                   , "Page County Jail"                                        , "IA"   ,
    "POLK COUNTY JAIL"                   , "Polk County Jail"                                        , "IA"   ,
    "POTTAWATTAMIE COUNTY JAIL"          , "Pottawattamie County Jail"                               , "IA"   ,
    "SAC COUNTY JAIL"                    , "Sac County Jail"                                         , "IA"   ,
    "SCOTT COUNTY JAIL"                  , "Scott County Jail"                                       , "IA"   ,
    "SIOUX COUNTY JAIL"                  , "Sioux County Jail"                                       , "IA"   ,
    "STORY COUNTY JAIL"                  , "Story County Jail"                                       , "IA"   ,
    "TAMA CO JAIL"                       , "Tama County Jail"                                        , "IA"   ,
    "UNION COUNTY JAIL"                  , "Union County Jail"                                       , "IA"   ,
    "WAPELLO COUNTY JAIL"                , "Wapello County Jail"                                     , "IA"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Jail"                                  , "IA"   ,
    "WEBSTER COUNTY JAIL"                , "Webster County Jail"                                     , "IA"   ,
    "WOODBURY CO JUV DET CNTR."          , "Woodbury County Jail"                                    , "IA"   ,
    "WOODBURY COUNTY JAIL"               , "Woodbury County Jail"                                    , "IA"   ,
    "WORTH COUNTY JAIL"                  , "Worth County Jail"                                       , "IA"   ,
    "WRIGHT COUNTY JAIL"                 , "Wright County Jail"                                      , "IA"   ,
    "ADA COUNTY JAIL"                    , "Ada County Jail"                                         , "ID"   ,
    "BANNOCK COUNTY JAIL"                , "Bannock County Jail"                                     , "ID"   ,
    "BINGHAM COUNTY JAIL"                , "Bingham County Jail"                                     , "ID"   ,
    "BOUNDARY COUNTY"                    , "Boundary County Detention Facility"                      , "ID"   ,
    "CANYON COUNTY JAIL"                 , "Canyon County Jail"                                      , "ID"   ,
    "CLARK COUNTY JAIL"                  , "Clark County Jail"                                       , "ID"   ,
    "ELMORE COUNTY JAIL"                 , "Elmore County Jail"                                      , "ID"   ,
    "FREMONT COUNTY JAIL"                , "Fremont County Law Enforcement Center"                   , "ID"   ,
    "JEFFERSON COUNTY JAIL"              , "Jefferson County Jail"                                   , "ID"   ,
    "KOOTENAI COUNTY"                    , "Kootenai County Jail"                                    , "ID"   ,
    "POWER COUNTY JAIL"                  , "Power County Jail"                                       , "ID"   ,
    "SHOSHONE CO PUBLIC SAFETY FACILITY" , "Shoshone County Jail"                                    , "ID"   ,
    "COLES COUNTY JAIL"                  , "Coles County Jail"                                       , "IL"   ,
    "CUMBERLAND COUNTY JAIL"             , "Cumberland County Jail"                                  , "IL"   ,
    "DEWITT COUNTY JAIL"                 , "DeWitt County Jail"                                      , "IL"   ,
    "DUPAGE COUNTY JAIL"                 , "DuPage County Jail"                                      , "IL"   ,
    "FRANKLIN COUNTY JAIL"               , "Franklin County Jail"                                    , "IL"   ,
    "KANKAKEE COUNTY JAIL"               , "Kankakee County - Jerome Combs Detention Center"         , "IL"   ,
    "LEE COUNTY JAIL"                    , "Lee County Jail"                                         , "IL"   ,
    "MCHENRY COUNTY SHERIFF'S"           , "McHenry County Jail"                                     , "IL"   ,
    "MERCER COUNTY CORRECTIONS"          , "Mercer County Jail"                                      , "IL"   ,
    "OGLE COUNTY JAIL"                   , "Ogle County Jail"                                        , "IL"   ,
    "PEORIA COUNTY JUV DET CENTER"       , "Peoria County Jail"                                      , "IL"   ,
    "PERRY COUNTY JAIL"                  , "Perry County Jail"                                       , "IL"   ,
    "ROCK ISLAND COUNTY JAIL"            , "Rock Island County Jail"                                 , "IL"   ,
    "SANGAMON COUNTY JAIL"               , "Sangamon County Jail"                                    , "IL"   ,
    "ALLEN COUNTY JAIL"                  , "Allen County Jail"                                       , "IN"   ,
    "CLARK COUNTY JAIL"                  , "Clark County Jail"                                       , "IN"   ,
    "CLAY COUNTY JUSTICE CENTER"         , "Clay County Justice Center"                              , "IN"   ,
    "CLINTON COUNTY JAIL"                , "Clinton County Jail"                                     , "IN"   ,
    "ELKHART COUNTY JAIL"                , "Elkhart County Correctional Complex"                     , "IN"   ,
    "FLOYD COUNTY JAIL"                  , "Floyd County Jail"                                       , "IN"   ,
    "MARION COUNTY JAIL"                 , "Marion County Jail"                                      , "IN"   ,
    "MARION COUNTY JAIL"                 , "Marion County Jail II"                                   , "IN"   ,
    "BARTON COUNTY JAIL"                 , "Barton County Jail"                                      , "KS"   ,
    "BUTLER COUNTY JAIL"                 , "Butler County Jail"                                      , "KS"   ,
    "CLOUD COUNTY JAIL"                  , "Cloud County Jail"                                       , "KS"   ,
    "FINNEY COUNTY JAIL"                 , "Finney County Jail"                                      , "KS"   ,
    "FORD COUNTY JAIL"                   , "Ford County Jail"                                        , "KS"   ,
    "HAMILTON COUNTY JAIL"               , "Hamilton County Jail"                                    , "KS"   ,
    "HARPER COUNTY JAIL"                 , "Harper County Jail"                                      , "KS"   ,
    "JEFFERSON COUNTY JAIL"              , "Jefferson County Jail"                                   , "KS"   ,
    "KEARNY COUNTY JAIL"                 , "Kearny County Jail"                                      , "KS"   ,
    "KINGMAN COUNTY JAIL"                , "Kingman County Jail"                                     , "KS"   ,
    "PHILLIPS COUNTY JAIL"               , "Phillips County Jail"                                    , "KS"   ,
    "RICE COUNTY DET CENTER"             , "Rice County Jail"                                        , "KS"   ,
    "SALINE COUNTY JAIL"                 , "Saline County Jail"                                      , "KS"   ,
    "SEWARD COUNTY JAIL"                 , "Seward County Jail"                                      , "KS"   ,
    "SHAWNEE COUNTY DEPT OF CORR."       , "Shawnee County Adult Detention Center & Annex"           , "KS"   ,
    "STEVENS COUNTY JAIL"                , "Stevens County Jail"                                     , "KS"   ,
    "THOMAS COUNTY JAIL"                 , "Thomas County Jail"                                      , "KS"   ,
    "ADAIR COUNTY REGIONAL JAIL"         , "Adair County Regional Jail"                              , "KY"   ,
    "BOONE COUNTY JAIL"                  , "Boone County Jail Workcamp"                              , "KY"   ,
    "BOONE COUNTY JAIL"                  , "Boone County Jail"                                       , "KY"   ,
    "BOURBON CO DET CENTER"              , "Bourbon County Regional Detention Center"                , "KY"   ,
    "CAMPBELL CO DET CTR"                , "Campbell County Detention Center"                        , "KY"   ,
    "CHRISTIAN COUNTY JAIL"              , "Christian County Jail"                                   , "KY"   ,
    "DAVIESS COUNTY DETENTION CENTER"    , "Daviess County Detention Center"                         , "KY"   ,
    "FRANKLIN CO. REGION JAIL"           , "Franklin County Regional Jail"                           , "KY"   ,
    "GRAYSON COUNTY DET CENTER (FEMALE)" , "Grayson County Detention Center"                         , "KY"   ,
    "GRAYSON COUNTY DETENTION CENTER"    , "Grayson County Detention Center"                         , "KY"   ,
    "HOPKINS COUNTY JAIL"                , "Hopkins County Jail"                                     , "KY"   ,
    "KENTON CO DETENTION CTR"            , "Kenton County Detention Center"                          , "KY"   ,
    "OLDHAM COUNTY JAIL"                 , "Oldham County Jail"                                      , "KY"   ,
    "PULASKI COUNTY DETENTION CENTER"    , "Pulaski County Detention Center"                         , "KY"   ,
    "SCOTT COUNTY DETENTION CENTER"      , "Scott County Detention Center"                           , "KY"   ,
    "WARREN COUNTY REGIONAL"             , "Warren County Regional Jail"                             , "KY"   ,
    "WOODFORD COUNTY SHERIFF/JAIL"       , "Woodford County Detention Center"                        , "KY"   ,
    "ALLEN PARISH PUBLIC SAFETY COMPLEX" , "Allen Parish Public Safety Complex"                      , "LA"   ,
    "AVOYELLES WOMEN'S CORR CN"          , "Avoyelles Parish Womens Correctional Center-DC3"         , "LA"   ,
    "BEAUREGARD PARISH JAIL"             , "Beauregard Parish Jail"                                  , "LA"   ,
    "CALCASIEU PARISH PRISON"            , "Calcasieu Sheriffs Prison"                               , "LA"   ,
    "CATAHOULA CORRECTIONAL CENTER"      , "Catahoula Correctional Center"                           , "LA"   ,
    "IBERIA PARISH JAIL"                 , "Iberia Parish Jail"                                      , "LA"   ,
    "MADISON PARISH DET CENTER"          , "Madison Parish Jail"                                     , "LA"   ,
    "NATCHITOCHES PARISH DET. CENTER"    , "Natchitoches Detention Center"                           , "LA"   ,
    "NELSON COLEMAN CORRECTIONS CENTER"  , "Nelson Coleman Correctional Center"                      , "LA"   ,
    "ST MARTIN PARISH CORR CNT"          , "St. Martin Parish Correctional Center Jail 1"            , "LA"   ,
    "ST MARTIN PARISH MEDICAL"           , "St. Martin Parish Correctional Center Jail 1"            , "LA"   ,
    "ST. MARTIN PARISH PRISON"           , "St. Martin Parish Correctional Center Jail 1"            , "LA"   ,
    "SULPHUR CITY"                       , "Sulphur City Jail"                                       , "LA"   ,
    "WEST BATON ROUGE DET CTR"           , "West Baton Rouge Parish Jail"                            , "LA"   ,
    "WEST MONROE CORR. DEPT"             , "West Monroe Correctional Center"                         , "LA"   ,
    "BARNSTABLE COUNTY"                  , "Barnstable County Correctional Facility"                 , "MA"   ,
    "FRANKLIN HOUSE OF CORRECTIONS"      , "Franklin County Jail & House of Corrections"             , "MA"   ,
    "CARROLL COUNTY DETENTION CENTER"    , "Carroll County Detention Center"                         , "MD"   ,
    "DORCHESTER CO DET CNTR"             , "Dorchester County Detention Center"                      , "MD"   ,
    "FREDERICK COUNTY DET. CEN"          , "Frederick County Adult Detention Center"                 , "MD"   ,
    "MONTGOMERY COUNTY DET."             , "Montgomery County Correctional Facility"                 , "MD"   ,
    "MONTGOMERY COUNTY DET."             , "Montgomery County Detention Center"                      , "MD"   ,
    "ORDNANCE ROAD CORRECTIONAL CENTER"  , "Anne Arundel County - Ordnance Road Correctional Center" , "MD"   ,
    "ST. MARY'S CO DET CNTR"             , "St. Marys County Detention Center"                       , "MD"   ,
    "WASHINGTON CO. DETENTION"           , "Washington County Detention Center"                      , "MD"   ,
    "WICOMICO CO DET"                    , "Wicomico County Detention Center"                        , "MD"   ,
    "WORCESTER CO. JAIL"                 , "Worcester County Jail"                                   , "MD"   ,
    "ANDROSCOGGIN COUNTY JAIL"           , "Androscoggin County Jail"                                , "ME"   ,
    "CUMBERLAND COUNTY JAIL"             , "Cumberland County Jail"                                  , "ME"   ,
    "FRANKLIN COUNTY JAIL, ME"           , "Franklin County Jail"                                    , "ME"   ,
    "HANCOCK COUNTY JAIL"                , "Hancock County Jail"                                     , "ME"   ,
    "KENNEBEC COUNTY JAIL"               , "Kennebec County Jail"                                    , "ME"   ,
    "PENOBSCOT COUNTY JAIL"              , "Penobscot County Jail"                                   , "ME"   ,
    "PISCATAGUIS COUNTY JAIL"            , "Piscataquis County Jail"                                 , "ME"   ,
    "SOMERSET COUNTY JAIL"               , "Somerset County Jail"                                    , "ME"   ,
    "TWO BRIDGES REGIONAL JAIL"          , "Two Bridges Regional Jail"                               , "ME"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Jail"                                  , "ME"   ,
    "YORK COUNTY JAIL"                   , "York County Jail"                                        , "ME"   ,
    "ISABELLA COUNTY JAIL"               , "Isabella County Jail"                                    , "MI"   ,
    "KALAMAZOO CO.KALAMAZOO.MI"          , "Kalamazoo County Jail"                                   , "MI"   ,
    "LAPEER CO., LAPEER. MI."            , "Lapeer County Jail"                                      , "MI"   ,
    "MACOMB CO.MT.CLEMENS,MI."           , "Macomb County Jail"                                      , "MI"   ,
    "MONROE COUNTY DETENTION-DORM"       , "Monroe County Jail"                                      , "MI"   ,
    "MONROE COUNTY DETENTION-DORM"       , "Monroe County Dormitory"                                 , "MI"   ,
    "MONROE COUNTY SHERIFF/JAIL-MAIN"    , "Monroe County Jail"                                      , "MI"   ,
    "MUSKEGON COUNTY JAIL"               , "Muskegon County Jail"                                    , "MI"   ,
    "OTTAWA COUNTY JAIL"                 , "Ottawa County Jail"                                      , "MI"   ,
    "ST JOSEPH CO,CENTREVILLE,"          , "St. Joseph County Jail"                                  , "MI"   ,
    "ST. CLAIR COUNTY JAIL"              , "St. Clair County Jail"                                   , "MI"   ,
    "VAN BUREN COUNTY JAIL, MI"          , "Van Buren County Jail"                                   , "MI"   ,
    "WASHTENAW CO, AN ARBOR,MI"          , "Washtenaw County Jail"                                   , "MI"   ,
    "ANOKA CO. JUVENILE CENTER"          , "Anoka County Jail"                                       , "MN"   ,
    "ANOKA COUNTY JAIL"                  , "Anoka County Jail"                                       , "MN"   ,
    "BENTON COUNTY JAIL"                 , "Benton County Jail"                                      , "MN"   ,
    "CARVER COUNTY JAIL"                 , "Carver County Jail"                                      , "MN"   ,
    "CROW WING COUNTY JAIL"              , "Crow Wing County Jail"                                   , "MN"   ,
    "HENNEPIN COUNTY ADC"                , "Hennepin County Workhouse"                               , "MN"   ,
    "HENNIPEN COUNTY WORKHOUSE"          , "Hennepin County Workhouse"                               , "MN"   ,
    "HENNIPEN COUNTY WORKHOUSE"          , "Hennepin County Jail"                                    , "MN"   ,
    "KITTSON CO. JAIL"                   , "Kittson County Jail"                                     , "MN"   ,
    "LAKE OF THE WOODS COUNTY JAIL"      , "Lake of the Woods County Jail"                           , "MN"   ,
    "LYON COUNTY JAIL"                   , "Lyon County Jail"                                        , "MN"   ,
    "OLMSTED CO. JAIL"                   , "Olmsted County Adult Detention Center"                   , "MN"   ,
    "PENNINGTON CO. JAIL, MN"            , "Pennington County Law Enforcement Center"                , "MN"   ,
    "RICE COUNTY JAIL"                   , "Rice County Jail"                                        , "MN"   ,
    "ROSEAU COUNTY JAIL"                 , "Roseau County Jail"                                      , "MN"   ,
    "SCOTT COUNTY JAIL"                  , "Scott County Jail"                                       , "MN"   ,
    "SHERBURNE COUNTY JAIL"              , "Sherburne County Jail"                                   , "MN"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Jail"                                  , "MN"   ,
    "AUDRAIN COUNTY JAIL"                , "Audrain County Jail"                                     , "MO"   ,
    "CALDWELL COUNTY JAIL"               , "Caldwell County Jail"                                    , "MO"   ,
    "CALLAWAY COUNTY JAIL"               , "Callaway County Jail"                                    , "MO"   ,
    "CLAY COUNTY JUVENILE"               , "Clay County Detention Center"                            , "MO"   ,
    "CLINTON COUNTY JAIL"                , "Clinton County Jail"                                     , "MO"   ,
    "GREENE COUNTY JAIL"                 , "Greene County Jail"                                      , "MO"   ,
    "JASPER CO. JUVENILE"                , "Jasper County Jail"                                      , "MO"   ,
    "JASPER COUNTY JAIL"                 , "Jasper County Jail"                                      , "MO"   ,
    "MONTGOMERY COUNTY JAIL"             , "Montgomery County Jail"                                  , "MO"   ,
    "MORGAN COUNTY SHERIFF'S DEPT"       , "Morgan County Adult Detention Center"                    , "MO"   ,
    "NEWTON COUNTY JAIL"                 , "Newton County Jail"                                      , "MO"   ,
    "OZARK COUNTY SHERIFF'S OFFICE"      , "Ozark County Jail"                                       , "MO"   ,
    "PHELPS COUNTY JAIL"                 , "Phelps County Jail"                                      , "MO"   ,
    "PLATTE COUNTY JAIL"                 , "Platte County Jail"                                      , "MO"   ,
    "SCOTT COUNTY JAIL"                  , "Scott County Jail"                                       , "MO"   ,
    "ST. CHARLES COUNTY JAIL"            , "St. Charles County Jail"                                 , "MO"   ,
    "ST. CLAIR COUNTY JAIL"              , "St. Clair County Jail"                                   , "MO"   ,
    "ST. FRANCOIS COUNTY JAIL"           , "St. Francois County Jail"                                , "MO"   ,
    "ST. LOUIS COUNTY JAIL"              , "St. Louis County - Department of Justice Services"       , "MO"   ,
    "STE. GENEVIEVE COUNTY SHERIFF/JAIL" , "Ste. Genevieve County Jail"                              , "MO"   ,
    "STONE COUNTY JAIL"                  , "Stone County Law Enforcement Center"                     , "MO"   ,
    "WARREN COUNTY JUSTICE CTR"          , "Warren County Jail"                                      , "MO"   ,
    "HANCOCK CO PUB SFTY CPLX"           , "Hancock County Jail"                                     , "MS"   ,
    "HANCOCK COUNTY JAIL"                , "Hancock County Jail"                                     , "MS"   ,
    "HARRISON DETENTION CENTER"          , "Harrison County Adult Detention Center"                  , "MS"   ,
    "TALLAHATCHIE CO CORR FACILITY"      , "Tallahatchie County Jail Number 2"                       , "MS"   ,
    "TALLAHATCHIE CO CORR FACILITY"      , "Tallahatchie County Correctional Facility - CCA"         , "MS"   ,
    "BEAVERHEAD CO DET CENTER"           , "Beaverhead County Jail"                                  , "MT"   ,
    "CASCADE COUNTY JAIL, MT"            , "Cascade County Adult Correctional Facility"              , "MT"   ,
    "CHOUTEAU COUNTY JAIL"               , "Chouteau County Jail"                                    , "MT"   ,
    "CUSTER COUNTY JAIL"                 , "Custer County Detention Center"                          , "MT"   ,
    "DAWSON COUNTY JAIL"                 , "Dawson County Jail"                                      , "MT"   ,
    "HILL COUNTY JUSTICE CENTER"         , "Hill County Jail"                                        , "MT"   ,
    "JEFFERSON COUNTY JAIL"              , "Jefferson County Jail"                                   , "MT"   ,
    "LAKE COUNTY JAIL"                   , "Lake County Jail"                                        , "MT"   ,
    "LEWIS & CLARK COUNTY JAIL"          , "Lewis and Clark County Jail"                             , "MT"   ,
    "MISSOULA COUNTY"                    , "Missoula County Detention Facility"                      , "MT"   ,
    "PARK COUNTY DET CENTER"             , "Park County Jail"                                        , "MT"   ,
    "RAVALLI COUNTY JAIL"                , "Ravalli County Adult Detention Center"                   , "MT"   ,
    "ROSEBUD COUNTY JAIL"                , "Rosebud County Jail"                                     , "MT"   ,
    "SHERIDAN COUNTY JAIL"               , "Sheridan County Jail"                                    , "MT"   ,
    "TOOLE COUNTY JAIL"                  , "Toole County Jail"                                       , "MT"   ,
    "YELLOWSTONE COUNTY YOUTH SERVICES"  , "Yellowstone County Detention Facility"                   , "MT"   ,
    "ASHE COUNTY JAIL"                   , "Ashe County Jail"                                        , "NC"   ,
    "Cabarrus County Jail"               , "Cabarrus County Jail"                                    , "NC"   ,
    "FORSYTH COUNTY JAIL"                , "Forsyth County Jail"                                     , "NC"   ,
    "FRANKLIN COUNTY DETENTION CENTER"   , "Franklin County Detention Center"                        , "NC"   ,
    "HENDERSON COUNTY DET. FAC."         , "Henderson County Jail"                                   , "NC"   ,
    "MECKLENBURG (NC) CO JAIL"           , "Mecklenburg County Jail North"                           , "NC"   ,
    "MECKLENBURG (NC) CO JAIL"           , "Mecklenburg County Jail Central"                         , "NC"   ,
    "NEW HANOVER CO DET CENTER"          , "New Hanover County Sheriffs Office Detention Facility"   , "NC"   ,
    "PENDER COUNTY JAIL"                 , "Pender County Jail"                                      , "NC"   ,
    "WAKE COUNTY SHERIFF DEPT."          , "Wake County Detention Center"                            , "NC"   ,
    "BOTTINEAU CO. ND JAIL"              , "Bottineau County Jail"                                   , "ND"   ,
    "CASS COUNTY JAIL"                   , "Cass County Jail"                                        , "ND"   ,
    "GRAND FORKS CO. JUVENILE"           , "Grand Forks County Correctional Center"                  , "ND"   ,
    "GRAND FORKS COUNTY CORREC"          , "Grand Forks County Correctional Center"                  , "ND"   ,
    "PEMBINA COUNTY JAIL"                , "Pembina County Jail"                                     , "ND"   ,
    "RICHLAND CO. JAIL, ND"              , "Richland County Jail"                                    , "ND"   ,
    "STUTSMAN CO. JAIL, ND"              , "Stutsman County Correctional Center"                     , "ND"   ,
    "WALSH COUNTY JAIL"                  , "Walsh County Jail"                                       , "ND"   ,
    "WARD COUNTY JAIL"                   , "Ward County Detention Center"                            , "ND"   ,
    "ADAMS CO JAIL, NEBRASKA"            , "Adams County Jail"                                       , "NE"   ,
    "BOX BUTTE CO. JAIL"                 , "Box Butte County Jail"                                   , "NE"   ,
    "BUFFALO COUNTY JAIL"                , "Buffalo County Jail"                                     , "NE"   ,
    "BUTLER COUNTY JAIL"                 , "Butler County Detention"                                 , "NE"   ,
    "CEDAR COUNTY JAIL"                  , "Cedar County Jail"                                       , "NE"   ,
    "CHASE COUNTY JAIL"                  , "Chase County Jail"                                       , "NE"   ,
    "CUSTER COUNTY JAIL"                 , "Custer County Jail"                                      , "NE"   ,
    "DAKOTA COUNTY JAIL"                 , "Dakota County Jail"                                      , "NE"   ,
    "DAWSON COUNTY JAIL"                 , "Dawson County Jail"                                      , "NE"   ,
    "FILLMORE COUNTY JAIL"               , "Fillmore County Jail"                                    , "NE"   ,
    "FRONTIER COUNTY JAIL"               , "Frontier County Jail"                                    , "NE"   ,
    "FURNAS COUNTY JAIL"                 , "Furnas County Jail"                                      , "NE"   ,
    "GAGE COUNTY JAIL"                   , "Gage County Jail"                                        , "NE"   ,
    "HALL COUNTY SHERIFF"                , "Hall County Department of Corrections"                   , "NE"   ,
    "HAMILTON COUNTY JAIL, NEB"          , "Hamilton County Jail"                                    , "NE"   ,
    "HARLAN COUNTY JAIL"                 , "Harlan County Jail"                                      , "NE"   ,
    "JOHNSON COUNTY JAIL"                , "Johnson County Jail"                                     , "NE"   ,
    "KEARNEY COUNTY JAIL"                , "Kearney County Jail"                                     , "NE"   ,
    "KEITH COUNTY JAIL"                  , "Keith County Jail"                                       , "NE"   ,
    "KIMBALL COUNTY JAIL"                , "Kimball County Jail"                                     , "NE"   ,
    "LINCOLN COUNTY JAIL"                , "Lincoln County Detention Center"                         , "NE"   ,
    "MADISON COUNTY JAIL"                , "Madison County Jail"                                     , "NE"   ,
    "OTOE CO JAIL"                       , "Otoe County Jail"                                        , "NE"   ,
    "PHELPS COUNTY JAIL"                 , "Phelps County Correctional"                              , "NE"   ,
    "PLATTE COUNTY JAIL, NEBR."          , "Platte County Detention Facility"                        , "NE"   ,
    "RED WILLOW COUNTY JAIL"             , "Red Willow County Jail"                                  , "NE"   ,
    "SALINE COUNTY JAIL"                 , "Saline County Jail"                                      , "NE"   ,
    "SARPY COUNTY JAIL"                  , "Sarpy County Jail"                                       , "NE"   ,
    "SARPY COUNTY JUVENILE"              , "Sarpy County Jail"                                       , "NE"   ,
    "SAUNDERS COUNTY JAIL"               , "Saunders County Jail"                                    , "NE"   ,
    "SCOTTS BLUFF CO JAIL"               , "Scotts Bluff County Detention Center"                    , "NE"   ,
    "SEWARD COUNTY JAIL"                 , "Seward County Jail"                                      , "NE"   ,
    "THURSTON COUNTY JAIL"               , "Thurston County Jail"                                    , "NE"   ,
    "WASHINGTON CO JAIL, BLAIR"          , "Washington County Jail"                                  , "NE"   ,
    "YORK COUNTY SHERIFF'S OFFICE"       , "York County Jail"                                        , "NE"   ,
    "BELKNAP COUNTY JAIL"                , "Belknap County Department of Corrections"                , "NH"   ,
    "ROCKINGHAM COUNTY JAIL"             , "Rockingham County Department of Corrections"             , "NH"   ,
    "STRAFFORD CO DEPT OF CORR"          , "Strafford County Jail"                                   , "NH"   ,
    "CAMDEN COUNTY JAIL"                 , "Camden County Correctional Facility"                     , "NJ"   ,
    "ESSEX COUNTY JAIL"                  , "Essex County Correctional Facility"                      , "NJ"   ,
    "MERCER COUNTY JAIL"                 , "Mercer County Correctional Center"                       , "NJ"   ,
    "MONMOUTH COUNTY JAIL"               , "Monmouth County Correctional Institution"                , "NJ"   ,
    "PASSAIC COUNTY JAIL"                , "Passaic County Jail"                                     , "NJ"   ,
    "SALEM COUNTY CORRECTIONAL FACILITY" , "Salem County Correctional Facility"                      , "NJ"   ,
    "SUSSEX COUNTY JAIL"                 , "Sussex County - Keogh Dwyer Correctional Facility"       , "NJ"   ,
    "ARTESIA CITY JAIL"                  , "Artesia City Jail"                                       , "NM"   ,
    "BERNALILLO COUNTY DET CTR"          , "Bernalillo County Metropolitan Detention Center"         , "NM"   ,
    "CURRY COUNTY DET FAC"               , "Curry County Adult Detention Center"                     , "NM"   ,
    "DONA ANA COUNTY DETENTION FACILITY" , "Dona Ana County Detention Center"                        , "NM"   ,
    "LEA COUNTY JAIL"                    , "Lea County Detention Center"                             , "NM"   ,
    "OTERO CO PROCESSING CENTER"         , "Otero County Detention Center"                           , "NM"   ,
    "OTERO COUNTY DETENTION"             , "Otero County Detention Center"                           , "NM"   ,
    "OTERO COUNTY PRISON FACILITY"       , "Otero County Detention Center"                           , "NM"   ,
    "QUAY COUNTY JAIL"                   , "Quay County Detention Center"                            , "NM"   ,
    "SANTA FE COUNTY JAIL"               , "Santa Fe County Adult Detention Facility"                , "NM"   ,
    "WASHOE COUNTY JAIL"                 , "Washoe County Detention Center"                          , "NV"   ,
    "ALLEGANY COUNTY JAIL"               , "Allegany County Jail"                                    , "NY"   ,
    "BROOME COUNTY JAIL"                 , "Broome County Sheriffs Correctional Facility"            , "NY"   ,
    "CATTARAUGUS COUNTY JAIL"            , "Cattaraugus County Jail"                                 , "NY"   ,
    "CAYUGA COUNTY JAIL"                 , "Cayuga County Jail"                                      , "NY"   ,
    "CHAUTAUQUA COUNTY JAIL"             , "Chautauqua County Jail"                                  , "NY"   ,
    "CHEMUNG COUNTY JAIL"                , "Chemung County Jail"                                     , "NY"   ,
    "CHENANGO COUNTY JAIL"               , "Chenango County Jail"                                    , "NY"   ,
    "CLINTON COUNTY JAIL"                , "Clinton County Jail"                                     , "NY"   ,
    "DELAWARE COUNTY JAIL"               , "Delaware County Jail"                                    , "NY"   ,
    "ERIE COUNTY CORRECTIONAL"           , "Erie County Correctional Facility"                       , "NY"   ,
    "ERIE COUNTY CORRECTIONAL"           , "Erie County Holding Center"                              , "NY"   ,
    "ERIE COUNTY HOLDING CENTER"         , "Erie County Correctional Facility"                       , "NY"   ,
    "ERIE COUNTY HOLDING CENTER"         , "Erie County Holding Center"                              , "NY"   ,
    "ESSEX COUNTY JAIL"                  , "Essex County Correctional Facility"                      , "NY"   ,
    "FRANKLIN COUNTY JAIL"               , "Franklin County Jail"                                    , "NY"   ,
    "FULTON COUNTY JAIL"                 , "Fulton County Jail"                                      , "NY"   ,
    "GENESEE COUNTY JAIL"                , "Genesee County Jail"                                     , "NY"   ,
    "HERKIMER COUNTY JAIL"               , "Herkimer County Correctional Facility"                   , "NY"   ,
    "LEWIS COUNTY JAIL"                  , "Lewis County Jail"                                       , "NY"   ,
    "LIVINGSTON COUNTY JAIL"             , "Livingston County Jail"                                  , "NY"   ,
    "MADISON COUNTY JAIL"                , "Madison County Jail"                                     , "NY"   ,
    "MONROE COUNTY JAIL"                 , "Monroe County Jail"                                      , "NY"   ,
    "MONTGOMERY COUNTY JAIL"             , "Montgomery County Jail"                                  , "NY"   ,
    "NASSAU CO CORREC CENTER"            , "Nassau County Correctional Center"                       , "NY"   ,
    "ONONDAGA COUNTY JAIL"               , "Onondaga County Department of Corrections"               , "NY"   ,
    "ONONDAGA COUNTY JAIL"               , "Onondaga County Justice Center"                          , "NY"   ,
    "ONTARIO COUNTY JAIL"                , "Ontario County Jail"                                     , "NY"   ,
    "ORANGE COUNTY JAIL"                 , "Orange County Jail"                                      , "NY"   ,
    "ORLEANS COUNTY JAIL"                , "Orleans County Jail"                                     , "NY"   ,
    "OTSEGO COUNTY JAIL"                 , "Otsego County Jail"                                      , "NY"   ,
    "RENSSELAER CO SHERIFF"              , "Rensselaer County Jail"                                  , "NY"   ,
    "SCHNECTADY COUNTY JAIL"             , "Schenectady County Jail"                                 , "NY"   ,
    "ST LAWRENCE COUNTY JAIL"            , "St. Lawrence County Jail"                                , "NY"   ,
    "STEUBEN COUNTY JAIL"                , "Steuben County Jail"                                     , "NY"   ,
    "TIOGA COUNTY JAIL"                  , "Tioga County Jail"                                       , "NY"   ,
    "ULSTER CO JAIL KINGSTON"            , "Ulster County Jail"                                      , "NY"   ,
    "WAYNE COUNTY JAIL"                  , "Wayne County Jail"                                       , "NY"   ,
    "WYOMING COUNTY JAIL"                , "Wyoming County Jail"                                     , "NY"   ,
    "YATES COUNTY JAIL"                  , "Yates County Jail"                                       , "NY"   ,
    "ASHTABULA COUNTY JAIL"              , "Ashtabula County Jail"                                   , "OH"   ,
    "ASHTABULA COUNTY JAIL"              , "Ashtabula City Jail"                                     , "OH"   ,
    "BELMONT COUNTY JAIL"                , "Belmont County Jail"                                     , "OH"   ,
    "BROADVIEW HTS CITY JAIL"            , "Broadview Heights City Jail"                             , "OH"   ,
    "DELAWARE COUNTY JAIL"               , "Delaware County Jail"                                    , "OH"   ,
    "FRANKLIN COUNTY JAIL"               , "Franklin County Correctional Center I"                   , "OH"   ,
    "FRANKLIN COUNTY JAIL"               , "Franklin County Correctional Center II"                  , "OH"   ,
    "GEAUGA COUNTY JAIL (GEAUGOH)"       , "Geauga County Jail"                                      , "OH"   ,
    "GENEVA CITY JAIL"                   , "Geneva City Jail"                                        , "OH"   ,
    "LORAIN COUNTY JAIL"                 , "Lorain County Jail"                                      , "OH"   ,
    "MAHONING COUNTY JAIL"               , "Mahoning County Justice Center"                          , "OH"   ,
    "MAPLE HEIGHTS CITY JAIL"            , "Maple Heights City Jail"                                 , "OH"   ,
    "MEDINA COUNTY JAIL"                 , "Medina County Jail"                                      , "OH"   ,
    "MORROW CO. CORRECTIONAL FACILITY"   , "Morrow County Correctional Facility"                     , "OH"   ,
    "NORTH ROYALTON CITY JAIL"           , "North Royalton City Jail"                                , "OH"   ,
    "PAULDING COUNTY JAIL"               , "Paulding County Jail"                                    , "OH"   ,
    "PICKAWAY COUNTY JAIL"               , "Pickaway County Jail"                                    , "OH"   ,
    "STARK COUNTY JAIL"                  , "Stark County Jail"                                       , "OH"   ,
    "TRUMBULL COUNTY JAIL"               , "Trumbull County Jail"                                    , "OH"   ,
    "WAYNE COUNTY JAIL"                  , "Wayne County Jail"                                       , "OH"   ,
    "CANADIAN COUNTY, EL RENO,"          , "Canadian County Jail"                                    , "OK"   ,
    "CARTER COUNTY, ARDMORE OK"          , "Carter County Detention Center"                          , "OK"   ,
    "CHEROKEE COUNTY JAIL"               , "Cherokee County Jail"                                    , "OK"   ,
    "CLEVELAND COUNTY, NORMAN"           , "Cleveland County Detention Center"                       , "OK"   ,
    "GARVIN COUNTY JAIL"                 , "Garvin County Jail"                                      , "OK"   ,
    "GRADY COUNTY LAW ENFORCEMENT CTR"   , "Grady County Jail"                                       , "OK"   ,
    "JEFFERSON COUNTY JAIL"              , "Jefferson County Jail"                                   , "OK"   ,
    "OKLAHOMA COUNTY JAIL"               , "Oklahoma County Jail"                                    , "OK"   ,
    "BENTON COUNTY JAIL"                 , "Benton County Jail"                                      , "OR"   ,
    "CLATSOP CO JAIL"                    , "Clatsop County Corrections Facility"                     , "OR"   ,
    "COLUMBIA COUNTY JAIL"               , "Columbia County Jail"                                    , "OR"   ,
    "COOS CO. JAIL"                      , "Coos County Jail"                                        , "OR"   ,
    "CURRY COUNTY JAIL"                  , "Curry County Jail"                                       , "OR"   ,
    "DESCHUTES CO JAIL"                  , "Deschutes County Adult Jail"                             , "OR"   ,
    "DOUGLAS CO. JAIL"                   , "Douglas County Corrections"                              , "OR"   ,
    "GRANT COUNTY JAIL"                  , "Grant County Jail"                                       , "OR"   ,
    "JACKSON COUNTY JUVENILE"            , "Jackson County Jail"                                     , "OR"   ,
    "JEFFERSON CO JAIL"                  , "Jefferson County Jail"                                   , "OR"   ,
    "JOSEPHINE CO. JAIL"                 , "Josephine County Adult Jail"                             , "OR"   ,
    "KLAMATH CO JAIL"                    , "Klamath County Jail"                                     , "OR"   ,
    "LINCOLN COUNTY JAIL"                , "Lincoln County Jail"                                     , "OR"   ,
    "LINN CO JAIL"                       , "Linn County Jail"                                        , "OR"   ,
    "MALHEUR COUNTY JAIL"                , "Malheur County Jail"                                     , "OR"   ,
    "MARION CO JAIL"                     , "Marion County Jail"                                      , "OR"   ,
    "MULTNOMAH COUNTY JAIL"              , "Multnomah County Inverness Jail"                         , "OR"   ,
    "MULTNOMAH COUNTY JAIL"              , "Multnomah County Detention Center"                       , "OR"   ,
    "NORTHERN OREGON CORR.FAC."          , "Northern Oregon Regional Corrections Facility"           , "OR"   ,
    "SPRINGFIELD CITY JAIL"              , "Springfield Municipal Jail"                              , "OR"   ,
    "TILLAMOOK COUNTY JAIL"              , "Tillamook County Jail"                                   , "OR"   ,
    "YAMHILL COUNTY CORRECTION"          , "Yamhill County Correctional Facility"                    , "OR"   ,
    "ALLEGHENY CO. JAIL"                 , "Allegheny County Jail"                                   , "PA"   ,
    "BEAVER COUNTY JAIL"                 , "Beaver County Jail"                                      , "PA"   ,
    "BERKS COUNTY RESIDENTIAL CENTER"    , "Berks County Jail System"                                , "PA"   ,
    "BERKS COUNTY SECURED JUVENILE"      , "Berks County Jail System"                                , "PA"   ,
    "CAMBRIA COUNTY JAIL, PA"            , "Cambria County Prison"                                   , "PA"   ,
    "CARBON COUNTY CORRECTIONL"          , "Carbon County Correctional Facility"                     , "PA"   ,
    "CHESTER CNTY JAIL, PA"              , "Chester County Prison"                                   , "PA"   ,
    "CLARION  COUNTY CORRECTIONS"        , "Clarion County Correctional Facility"                    , "PA"   ,
    "CLEARFIELD CO. JAIL, PA"            , "Clearfield County Prison"                                , "PA"   ,
    "DAUPHIN CNTY JAIL, PA"              , "Dauphin County Prison"                                   , "PA"   ,
    "ERIE COUNTY JAIL, PA"               , "Erie County Prison"                                      , "PA"   ,
    "FRANKLIN COUNTY JAIL"               , "Franklin County Jail"                                    , "PA"   ,
    "LACKAWANA CNTY JAIL, PA"            , "Lackawanna County Prison"                                , "PA"   ,
    "MERCER CO. JAIL, PA"                , "Mercer County Jail"                                      , "PA"   ,
    "MONTGOMERY CNTY JAIL, PA"           , "Montgomery County Correctional Facility"                 , "PA"   ,
    "PIKE COUNTY JAIL"                   , "Pike County Correctional Facility"                       , "PA"   ,
    "PIKE COUNTY JAIL"                   , "Pike County Correctional Facility"                       , "PA"   ,
    "SNYDER COUNTY JAIL"                 , "Snyder County Prison"                                    , "PA"   ,
    "SOMERSET COUNTY JAIL"               , "Somerset County Jail"                                    , "PA"   ,
    "WARREN COUNTY JAIL"                 , "Warren County Prison"                                    , "PA"   ,
    "WASHINGTON CO. JAIL, PA"            , "Washington County Correctional Facility"                 , "PA"   ,
    "WESTMORELAND COUNTY JAIL"           , "Westmoreland County Prison"                              , "PA"   ,
    "DORCHESTER CO DET CTR"              , "Dorchester County Detention Center"                      , "SC"   ,
    "YORK COUNTY DETENTION CENTER"       , "York County Prison"                                      , "SC"   ,
    "YORK COUNTY DETENTION CENTER"       , "York County Detention Center"                            , "SC"   ,
    "BROOKINGS CO , SD JAIL"             , "Brookings County Detention Center"                       , "SD"   ,
    "BROWN COUNTY JAIL"                  , "Brown County Jail"                                       , "SD"   ,
    "BRULE COUNTY JAIL"                  , "Brule County Jail"                                       , "SD"   ,
    "CLAY COUNTY JAIL"                   , "Clay County Jail"                                        , "SD"   ,
    "DAVISON COUNTY, SD"                 , "Davison County Jail"                                     , "SD"   ,
    "HUGHES CO. JAIL"                    , "Hughes County Jail"                                      , "SD"   ,
    "LAWRENCE CO. JAIL, SD"              , "Lawrence County Jail"                                    , "SD"   ,
    "MEADE CO. JAIL, SD"                 , "Meade County Jail"                                       , "SD"   ,
    "MINNEHAHA COUNTY JAIL"              , "Minnehaha County Jail"                                   , "SD"   ,
    "PENNINGTON COUNTY JAIL SD"          , "Pennington County Jail"                                  , "SD"   ,
    "ROBERTS CO. JAIL, SD"               , "Roberts County Jail"                                     , "SD"   ,
    "UNION COUNTY JAIL"                  , "Union County Jail"                                       , "SD"   ,
    "BLOUNT COUNTY JUSTICE CTR"          , "Blount County Detention Facility"                        , "TN"   ,
    "BLOUNT COUNTY JUV DET CENTER"       , "Blount County Detention Facility"                        , "TN"   ,
    "GREENE COUNTY SHERIFF, TN"          , "Greene County Detention Center"                          , "TN"   ,
    "HAMBLEN COUNTY JAIL"                , "Hamblen County Jail"                                     , "TN"   ,
    "HAMILTON CO. JAIL (TENN)"           , "Hamilton County Jail"                                    , "TN"   ,
    "KNOX COUNTY DETENTION FACILITY"     , "Knox County Jail"                                        , "TN"   ,
    "KNOX COUNTY SHERIFF"                , "Knox County Jail"                                        , "TN"   ,
    "PUTNAM COUNTY SHERIFF"              , "Putnam County Jail"                                      , "TN"   ,
    "RUTHERFORD COUNTY SHERIFF"          , "Rutherford County Adult Detention Center"                , "TN"   ,
    "SEVIER COUNTY JAIL"                 , "Sevier County Jail & Minimum Security Facility"          , "TN"   ,
    "SILVERDALE/HAMILTON COUNTY"         , "Silverdale Correction Facility - CCA"                    , "TN"   ,
    "WILLIAMSON COUNTY JAIL"             , "Williamson County Jail"                                  , "TN"   ,
    "ANGELINA COUNTY JAIL"               , "Angelina County Jail"                                    , "TX"   ,
    "ATASCOSA COUNTY JAIL"               , "Atascosa County Jail"                                    , "TX"   ,
    "BASTROP COUNTY JAIL"                , "Bastrop County Jail"                                     , "TX"   ,
    "BEXAR COUNTY WACKENHUT ANNUAL DET." , "Bexar County Adult Detention Center"                     , "TX"   ,
    "BLANCO COUNTY JAIL"                 , "Blanco County Jail"                                      , "TX"   ,
    "BRAZOS COUNTY JAIL"                 , "Brazos County Detention Center"                          , "TX"   ,
    "BREWSTER COUNTY JAIL"               , "Brewster County Jail"                                    , "TX"   ,
    "BROOKS COUNTY JAIL (CONTRACT)"      , "Brooks County Detention Center"                          , "TX"   ,
    "BROOKS COUNTY JAIL, (SHERIFF)"      , "Brooks County Detention Center"                          , "TX"   ,
    "CALDWELL COUNTY JAIL"               , "Caldwell County Jail"                                    , "TX"   ,
    "COMAL CTY JAIL"                     , "Comal County Jail"                                       , "TX"   ,
    "COOKE COUNTY JAIL"                  , "Cooke County Jail"                                       , "TX"   ,
    "CORYELL COUNTY JAIL"                , "Coryell County Jail"                                     , "TX"   ,
    "DE WITT COUNTY JAIL"                , "DeWitt County Jail"                                      , "TX"   ,
    "DENTON COUNTY JAIL"                 , "Denton County Jail"                                      , "TX"   ,
    "DICKENS COUNTY DET. CENTER"         , "Dickens County Jail"                                     , "TX"   ,
    "ECTOR COUNTY CORRECTION CENTER"     , "Ector County Law Enforcement Center"                     , "TX"   ,
    "ECTOR COUNTY L.E.C."                , "Ector County Law Enforcement Center"                     , "TX"   ,
    "EL PASO COUNTY JAIL (TX)"           , "El Paso County Detention Facility - Annex"               , "TX"   ,
    "FAYETTE COUNTY JAIL"                , "Fayette County Justice Center"                           , "TX"   ,
    "GONZALES COUNTY JAIL"               , "Gonzales County Jail"                                    , "TX"   ,
    "GRAYSON COUNTY JAIL"                , "Grayson County Jail"                                     , "TX"   ,
    "GUADALUPE CTY JAIL"                 , "Guadalupe County Detention Center"                       , "TX"   ,
    "HENDERSON COUNTY JAIL"              , "Henderson County Jail"                                   , "TX"   ,
    "HIDALGO COUNTY SHERIFF'S JAIL"      , "Hidalgo County Adult Detention Center"                   , "TX"   ,
    "HUDSPETH COUNTY JAIL"               , "Hudspeth County Jail"                                    , "TX"   ,
    "JACK HARWELL DETENTION CENTER"      , "Jack Harwell Detention Center - LaSalle"                 , "TX"   ,
    "JACKSON COUNTY JAIL"                , "Jackson County Jail"                                     , "TX"   ,
    "JOHNSON COUNTY JAIL"                , "Johnson County Jail"                                     , "TX"   ,
    "KARNES COUNTY CIVIL DET. FACILITY"  , "Karnes County Jail"                                      , "TX"   ,
    "KENDALL COUNTY JAIL"                , "Kendall County Jail"                                     , "TX"   ,
    "KERR COUNTY JAIL"                   , "Kerr County Jail"                                        , "TX"   ,
    "KERR COUNTY JDC"                    , "Kerr County Jail"                                        , "TX"   ,
    "KIMBLE COUNTY JAIL"                 , "Kimble County Jail"                                      , "TX"   ,
    "LASALLE COUNTY JAIL"                , "LaSalle County Jail"                                     , "TX"   ,
    "LAVACA COUNTY JAIL"                 , "Lavaca County Jail"                                      , "TX"   ,
    "LEE COUNTY JAIL"                    , "Lee County Jail"                                         , "TX"   ,
    "LIBERTY COUNTY JAIL"                , "Liberty County Jail- Geo Group"                          , "TX"   ,
    "LIMESTONE COUNTY JAIL"              , "Limestone County Jail"                                   , "TX"   ,
    "LIMESTONE COUNTY JAIL"              , "Limestone County Detention Center"                       , "TX"   ,
    "LIMESTONE DET CENTER"               , "Limestone County Detention Center"                       , "TX"   ,
    "MARTIN COUNTY JAIL"                 , "Martin County Jail"                                      , "TX"   ,
    "MCCLENNAN COUNTY DETENTION CENTER"  , "McLennan County Jail"                                    , "TX"   ,
    "MCLENNAN COUNTY JAIL"               , "McLennan County Jail"                                    , "TX"   ,
    "MONTGOMERY COUNTY JAIL"             , "Montgomery County Jail"                                  , "TX"   ,
    "NAVARRO CO JUSTICE CTR"             , "Navarro County Justice Center"                           , "TX"   ,
    "NEWTON COUNTY CORR. CTR."           , "Newton County Jail"                                      , "TX"   ,
    "PRESIDIO COUNTY JAIL"               , "Presidio County Jail"                                    , "TX"   ,
    "RANDALL COUNTY JAIL"                , "Randall County Jail"                                     , "TX"   ,
    "REEVES COUNTY DET. CENTER"          , "Reeves County Jail"                                      , "TX"   ,
    "REEVES COUNTY JAIL"                 , "Reeves County Jail"                                      , "TX"   ,
    "RUNNELS COUNTY JAIL"                , "Runnels County Jail"                                     , "TX"   ,
    "SAN PATRICIO COUNTY JAIL"           , "San Patricio County Jail"                                , "TX"   ,
    "SOMERVELL COUNTY SHERIFF'S DEPT."   , "Somervell County Jail"                                   , "TX"   ,
    "STARR COUNTY JAIL"                  , "Starr County Jail"                                       , "TX"   ,
    "SUTTON COUNTY JAIL"                 , "Sutton County Jail"                                      , "TX"   ,
    "TARRANT COUNTY JAIL"                , "Tarrant County - Correctional Center"                    , "TX"   ,
    "TITUS COUNTY JAIL"                  , "Titus County Jail"                                       , "TX"   ,
    "TRAVIS COUNTY JAIL"                 , "Travis County Correctional Complex"                      , "TX"   ,
    "UPSHUR COUNTY JAIL"                 , "Upshur County Jail"                                      , "TX"   ,
    "VICTORIA COUNTY JAIL"               , "Victoria County Jail"                                    , "TX"   ,
    "WALKER COUNTY JAIL"                 , "Walker County Jail"                                      , "TX"   ,
    "WEBB COUNTY DETENTION CENTER (CCA)" , "Webb County Jail"                                        , "TX"   ,
    "WEBB COUNTY JAIL"                   , "Webb County Jail"                                        , "TX"   ,
    "WHARTON COUNTY JAIL"                , "Wharton County Jail"                                     , "TX"   ,
    "WILLACY CO  REGIONAL DETN FACIL"    , "Willacy County Jail"                                     , "TX"   ,
    "WILLIAMSON COUNTY JAIL"             , "Williamson County Jail"                                  , "TX"   ,
    "WILSON COUNTY JAIL"                 , "Wilson County Jail"                                      , "TX"   ,
    "WINKLER COUNTY JAIL"                , "Winkler County Jail"                                     , "TX"   ,
    "WISE COUNTY JAIL"                   , "Wise County Jail"                                        , "TX"   ,
    "ZAPATA COUNTY JAIL"                 , "Zapata County Regional Jail"                             , "TX"   ,
    "ZAVALA COUNTY JAIL"                 , "Zavala County Jail"                                      , "TX"   ,
    "DAVIS CO. JAIL"                     , "Davis County Jail"                                       , "UT"   ,
    "JUAB COUNTY JAIL"                   , "Juab County Jail"                                        , "UT"   ,
    "SALT LAKE COUNTY JAIL"              , "Salt Lake County Jail"                                   , "UT"   ,
    "SUMMIT COUNTY JAIL"                 , "Summit County Jail"                                      , "UT"   ,
    "UINTAH COUNTY JAIL"                 , "Uintah County Jail"                                      , "UT"   ,
    "UTAH COUNTY JAIL"                   , "Utah County Jail"                                        , "UT"   ,
    "WASATCH COUNTY JAIL"                , "Wasatch County Jail"                                     , "UT"   ,
    "WASHINGTON COUNTY JAIL"             , "Washington County Jail"                                  , "UT"   ,
    "WEBER COUNTY JAIL"                  , "Weber County Correctional Facility"                      , "UT"   ,
    "ALBEMARLE-CHARLOTTESVILLE"          , "Albemarle Charlottesville Regional Jail"                 , "VA"   ,
    "ARLINGTON CO JAIL"                  , "Arlington County Detention Facility"                     , "VA"   ,
    "CENTRAL VA REGIONAL JAIL"           , "Central Virginia Regional Jail"                          , "VA"   ,
    "CHESAPEAKE CITY JAIL"               , "Chesapeake City Jail"                                    , "VA"   ,
    "CHESTERFIELD CO. JAIL"              , "Chesterfield County Jail"                                , "VA"   ,
    "CULPEPER CO. ADULT DET. CENTER"     , "Culpeper County Jail"                                    , "VA"   ,
    "FAIRFAX CO JAIL"                    , "Fairfax County Adult Detention Center"                   , "VA"   ,
    "FAIRFAX CO. ADULT DETENTION CENTER" , "Fairfax County Adult Detention Center"                   , "VA"   ,
    "HAMPTON ROADS REGIONAL JAIL"        , "Hampton Roads Regional Jail"                             , "VA"   ,
    "HENRICO COUNTY JAIL"                , "Henrico County Regional Jail East - New Kent County"     , "VA"   ,
    "LOUDOUN COUNTY"                     , "Loudoun County Adult Detention Center"                   , "VA"   ,
    "MIDDLE RIVER REGIONAL JAIL"         , "Middle River Regional Jail"                              , "VA"   ,
    "NEW RIVER VALLEY REG. JAIL"         , "New River Valley Regional Jail"                          , "VA"   ,
    "NORFOLK CITY JAIL"                  , "Norfolk City Jail"                                       , "VA"   ,
    "PAMUNKEY REG JAIL"                  , "Pamunkey Regional Jail"                                  , "VA"   ,
    "PIEDMONT REG JAIL"                  , "Piedmont Regional Jail"                                  , "VA"   ,
    "RICHMOND CITY JAIL"                 , "Richmond City Jail"                                      , "VA"   ,
    "RIVERSIDE REG JAIL"                 , "Riverside Regional Jail"                                 , "VA"   ,
    "ROANOKE CITY JAIL"                  , "Roanoke City Jail"                                       , "VA"   ,
    "ROCKINGHAM COUNTY JAIL"             , "Rockingham-Harrisonburg Regional Jail"                   , "VA"   ,
    "VIRGINIA PENINSULA REG. JAIL"       , "Virginia Peninsula Regional Jail"                        , "VA"   ,
    "WESTERN TIDEWATER REG. JAIL"        , "Western Tidewater Regional Jail"                         , "VA"   ,
    "WESTERN VIRGINIA REGIONAL JAIL"     , "Western Virginia Regional Jail"                          , "VA"   ,
    "ABERDEEN CITY JAIL"                 , "Aberdeen City Jail"                                      , "WA"   ,
    "ADAMS COUNTY"                       , "Adams County Jail"                                       , "WA"   ,
    "CHELAN CO. REGIONAL JAIL"           , "Chelan County Regional Justice Center"                   , "WA"   ,
    "CLARK COUNTY JAIL"                  , "Clark County Jail and Work Center"                       , "WA"   ,
    "CLARK COUNTY JUVENILE"              , "Clark County Jail and Work Center"                       , "WA"   ,
    "FERRY COUNTY JAIL"                  , "Ferry County Jail"                                       , "WA"   ,
    "FRANKLIN COUNTY"                    , "Franklin County Jail"                                    , "WA"   ,
    "GRANT COUNTY"                       , "Grant County Jail"                                       , "WA"   ,
    "ISLAND COUNTY JAIL"                 , "Island County Jail"                                      , "WA"   ,
    "OKANOGAN CO. JAIL"                  , "Okanogan County Correctional Center"                     , "WA"   ,
    "PIERCE COUNTY JAIL"                 , "Pierce County Jail"                                      , "WA"   ,
    "SKAGIT COUNTY JAIL"                 , "Skagit County Jail"                                      , "WA"   ,
    "SPOKANE COUNTY"                     , "Spokane County Jail"                                     , "WA"   ,
    "STEVENS COUNTY JAIL"                , "Stevens County Jail"                                     , "WA"   ,
    "WHATCOM COUNTY JAIL"                , "Whatcom County Jail"                                     , "WA"   ,
    "WHATCOM COUNTY JAIL"                , "Whatcom County Work Center"                              , "WA"   ,
    "WHITMAN COUNTY JAIL"                , "Whitman County Jail"                                     , "WA"   ,
    "YAKIMA COUNTY"                      , "Yakima County DOC - Main Jail"                           , "WA"   ,
    "BROWN COUNTY JAIL"                  , "Brown County Jail"                                       , "WI"   ,
    "DANE COUNTY JAIL"                   , "Dane County Jail System"                                 , "WI"   ,
    "DODGE COUNTY JAIL, JUNEAU"          , "Dodge County Detention Facility"                         , "WI"   ,
    "KENOSHA COUNTY JAIL"                , "Kenosha County Jail - Pre-Trial Detention Facility"      , "WI"   ,
    "KENOSHA COUNTY JAIL"                , "Kenosha County Detention Facility"                       , "WI"   ,
    "OZAUKEE COUNTY JAIL"                , "Ozaukee County Jail"                                     , "WI"   ,
    "PIERCE COUNTY JAIL"                 , "Pierce County Jail"                                      , "WI"   ,
    "RACINE COUNTY JAIL"                 , "Racine County Jail"                                      , "WI"   ,
    "SAUK COUNTY SHERIFF"                , "Sauk County Jail"                                        , "WI"   ,
    "ST. CROIX COUNTY JAIL"              , "St. Croix County Jail"                                   , "WI"   ,
    "WALWORTH COUNTY JAIL"               , "Walworth County Jail"                                    , "WI"   ,
    "WAUKESHA COUNTY JAIL"               , "Waukesha County Jail"                                    , "WI"   ,
    "WAUKESHA COUNTY JAIL"               , "Waukesha County Huber Facility"                          , "WI"   ,
    "CARBON COUNTY JAIL"                 , "Carbon County Jail"                                      , "WY"   ,
    "FREMONT COUNTY JAIL, WY"            , "Fremont County Detention Center"                         , "WY"   ,
    "GOSHEN COUNTY JAIL"                 , "Goshen County Detention Center"                          , "WY"   ,
    "LINCOLN COUNTY JAIL"                , "Lincoln County Jail"                                     , "WY"   ,
    "NIOBRARA COUNTY JAIL"               , "Niobrara County Criminal Justice Facility"               , "WY"   ,
    "PLATTE COUNTY JAIL"                 , "Platte County Detention Center"                          , "WY"   ,
    "SHERIDAN COUNTY JAIL"               , "Sheridan County Detention Center"                        , "WY"   ,
    "TETON COUNTY DETENTION CENTER"      , "Teton County Detention Center"                           , "WY"
  )
