library(tidyverse)
library(tidylog)

source("code/functions.R")

facility_attributes <- arrow::read_feather(
  "data/facilities-attributes-raw.feather"
)

hospital_list <-
  arrow::read_feather("data/hospitals.feather") |>
  distinct(name, state) |>
  mutate(name_join = clean_text(name))

facilities_from_detentions <-
  arrow::read_feather(
    "data/facilities-from-detentions.feather"
  ) |>
  mutate(name_join = clean_text(detention_facility)) |>
  filter(str_detect(name_join, "hosp|\\bmed\\b|health|clinic|emerg")) |>
  select(detention_facility_code, name = detention_facility, name_join) |>
  filter(!str_detect(detention_facility_code, "^BOP")) |>
  mutate(
    state = str_sub(detention_facility_code, -2),
    # state = case_when(
    #   !state_guess %in% c(state.abb, "PR") |
    #     str_sub(detention_facility_code, 1, 2) %in% c(state.abb, "PR") |
    #     str_sub(detention_facility_code, 1, 3) == "BOP" |
    #     nchar(detention_facility_code) < 7 ~ NA_character_,
    #   TRUE ~ state_guess
    # )
  )

# library(fuzzylink)

# matches_cleaned <-
#   fuzzylink::fuzzylink(
#     facilities_from_detentions,
#     hospital_list,
#     record_type = "names of medical facilities",
#     model = "gpt-3.5-turbo-instruct",
#     learner = "ranger",
#     instructions = "compare names of detention facilities to a list of hospitals and medical centers to find possible matches",
#     by = "name_join",
#     blocking.variables = "state",
#     max_labels = 50000,
#     openai_api_key = "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"
#   )

matches_cleaned <-
  tribble(
    ~name.x                              , ~name.y                                                             , ~state ,
    "UNIVERSITY MED CENTER OF EL PASO"   , "UNIVERSITY MEDICAL CENTER OF EL PASO"                              , "TX"   ,
    "VALLEY BAPTIST HOSPITAL"            , "VALLEY BAPTIST MEDICAL CENTER- BROWNSVILLE"                        , "TX"   ,
    "VALLEY BAPTIST HOSPITAL"            , "VALLEY BAPTIST MEDICAL CENTER - BROWNSVILLE"                       , "TX"   ,
    "CHRISTUS SPOHN HOSP CC - SOUTH"     , "CHRISTUS SPOHN HOSPITAL CORPUS CHRISTI"                            , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER - TEMPLE"                      , "TX"   ,
    "ASCENSION SETON WILLIAMS HOSP"      , "ASCENSION SETON MEDICAL CENTER AUSTIN"                             , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER AT IRVING"                     , "TX"   ,
    "HOUSTON HEALTHCARE HOSP"            , "HCA HOUSTON HEALTHCARE SOUTHEAST"                                  , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER HILLCREST"                     , "TX"   ,
    "MIDLAND MEMORIAL HOSPITAL"          , "MIDLAND MEMORIAL HOSPITAL"                                         , "TX"   ,
    "CHRISTUS SANTA ROSA HOSPITAL - MED" , "CHRISTUS SANTA ROSA MEDICAL CENTER"                                , "TX"   ,
    "HUNTSVILLE MEMORIAL HOSPITAL"       , "HUNTSVILLE MEMORIAL HOSPITAL"                                      , "TX"   ,
    "METHODIST HOSPITAL"                 , "HOUSTON METHODIST HOSPITAL"                                        , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST HOSPITAL"                                                , "TX"   ,
    "METHODIST HOSPITAL METROPOLITAN"    , "METHODIST HOSPITAL"                                                , "TX"   ,
    "METHODIST HOSPITAL NORTHEAST"       , "METHODIST HOSPITAL"                                                , "TX"   ,
    "METHODIST HOSPITAL STONE OAK"       , "METHODIST HOSPITAL"                                                , "TX"   ,
    "METHODIST HOSPITAL TEXSAN"          , "METHODIST HOSPITAL"                                                , "TX"   ,
    "METHODIST HOSPITAL SOUTH"           , "METHODIST HOSPITAL"                                                , "TX"   ,
    "MEMORIAL HERMANN NE HOSP"           , "MEMORIAL HERMANN MEMORIAL CITY HOSPITAL"                           , "TX"   ,
    "HOUSTON HEALTHCARE HOSP"            , "HCA HOUSTON HEALTHCARE NORTHWEST"                                  , "TX"   ,
    "MEMORIAL HERMANN NE HOSP"           , "MEMORIAL HERMANN NORTHEAST HOSPITAL"                               , "TX"   ,
    "RIO GRANDE ST.HOSPITAL"             , "RIO GRANDE REGIONAL HOSPITAL"                                      , "TX"   ,
    "ST LUKE'S HEALTH - THE WOODLANDS"   , "ST LUKE'S THE WOODLANDS HOSPITAL"                                  , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT &  WHITE MEDICAL CENTER - CENTENNIAL"                 , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER PLANO"                         , "TX"   ,
    "HASKELL MEMORIAL HOSPITAL"          , "HASKELL MEMORIAL HOSPITAL"                                         , "TX"   ,
    "OTTO KAISER MEMORIAL HOSPITAL"      , "OTTO KAISER MEMORIAL HOSPITAL"                                     , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER -TAYLOR"                       , "TX"   ,
    "DIMMIT REGIONAL HOSPITAL"           , "DIMMIT REGIONAL HOSPITAL"                                          , "TX"   ,
    "FRIO REGIONAL HOSPITAL"             , "FRIO REGIONAL HOSPITAL"                                            , "TX"   ,
    "KNOX COUNTY HOSPITAL"               , "KNOX COUNTY HOSPITAL"                                              , "TX"   ,
    "RED RIVER HOSPITAL"                 , "RED RIVER HOSPITAL"                                                , "TX"   ,
    "WEST OAKS HOSPITAL"                 , "WEST OAKS HOSPITAL"                                                , "TX"   ,
    "EL PASO BEHAVIORAL HEALTH SYSTEM"   , "EL PASO BEHAVIORAL HEALTH SYSTEM"                                  , "TX"   ,
    "GEORGETOWN BEHAVIORAL HOSPITAL"     , "GEORGETOWN BEHAVIORAL HEALTH INSTITUTE"                            , "TX"   ,
    "CROSS CREEK HOSPITAL"               , "CROSS CREEK HOSPITAL"                                              , "TX"   ,
    "PALMS BEHAVIORAL HEALTH"            , "PALMS BEHAVIORAL HEALTH"                                           , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER - ROUND ROCK"                  , "TX"   ,
    "ASCENSION SETON WILLIAMS HOSP"      , "ASCENSION SETON WILLIAMSON"                                        , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST HOSPITAL  STONE OAK"                                     , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST HOSPITAL - STONE OAK"                                    , "TX"   ,
    "METHODIST HOSPITAL STONE OAK"       , "METHODIST HOSPITAL  STONE OAK"                                     , "TX"   ,
    "METHODIST HOSPITAL STONE OAK"       , "METHODIST HOSPITAL - STONE OAK"                                    , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST HOSPITAL FOR SURGERY"                                    , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE  MEDICAL CENTER  MCKINNEY"                  , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - MCKINNEY"                  , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE STATI"                , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE FALLS"                , "TX"   ,
    "METHODIST HOSPITAL SOUTH"           , "METHODIST SOUTHLAKE MEDICAL CENTER"                                , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT & WHITE MEDICAL CENTER- AUSTIN"                       , "TX"   ,
    "ANSON GENERAL HOSPITAL"             , "ANSON GENERAL HOSPITAL"                                            , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE INSTITUTE FOR REHABILITATION - FRISCO"      , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE INSTITUTE FOR REHABILITATION - LAKEWAY"     , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - AUSTIN"                    , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - BRENHAM"                   , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - FRISCO"                    , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - HILLCREST"                 , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - LAKEWAY"                   , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - MARBLE FALLS"              , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - PLANO"                     , "TX"   ,
    "BAYLOR SCOTT WHITE MED RR"          , "BAYLOR SCOTT AND WHITE MEDICAL CENTER - TAYLOR"                    , "TX"   ,
    "CHI ST LUKE'S HEALTH MEM"           , "CHI ST LUKES HEALTH BAYLOR COLLEGE OF MEDICINE MEDICAL CENTER"     , "TX"   ,
    "ST LUKE'S HEALTH - THE WOODLANDS"   , "CHI ST LUKES HEALTH BAYLOR COLLEGE OF MEDICINE MEDICAL CENTER"     , "TX"   ,
    "CHRISTUS SANTA ROSA HOSPITAL - MED" , "CHRISTUS SANTA ROSA HOSPITAL - MEDICAL CENTER"                     , "TX"   ,
    "CHRISTUS SANTA ROSA HOSPITAL - MED" , "CHRISTUS SANTA ROSA HOSPITAL - NEW BRAUNFELS"                      , "TX"   ,
    "CHRISTUS SPOHN HOSP CC - SOUTH"     , "CHRISTUS SPOHN HOSPITAL CORPUS CHRISTI SHORELINE"                  , "TX"   ,
    "CHRISTUS SPOHN HOSP CC - SOUTH"     , "CHRISTUS SPOHN HOSPITAL CORPUS CHRISTI SOUTH"                      , "TX"   ,
    "EL PASO LTAC HOSPITAL"              , "EL PASO LTAC HOSPITAL"                                             , "TX"   ,
    "HARRIS HEALTH BEN TAUB HOSPITAL"    , "HARRIS HEALTH SYSTEM BEN TAUB HOSPITAL"                            , "TX"   ,
    "HARRIS HEALTH LBJ HOSPITAL"         , "HARRIS HEALTH SYSTEM LYNDON B JOHNSON HOSPITAL"                    , "TX"   ,
    "JOHN PETER SMITH HOSPITAL"          , "JOHN PETER SMITH HOSPITAL"                                         , "TX"   ,
    "MEMORIAL HERMANN NE HOSP"           , "MEMORIAL HERMANN GREATER HEIGHTS HOSPITAL"                         , "TX"   ,
    "MEMORIAL HERMANN NE HOSP"           , "MEMORIAL HERMANN SOUTHEAST HOSPITAL"                               , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST HOSPITAL SOUTH"                                          , "TX"   ,
    "METHODIST HOSPITAL SOUTH"           , "METHODIST HOSPITAL SOUTH"                                          , "TX"   ,
    "METHODIST HOSPITAL"                 , "METHODIST TEXSAN HOSPITAL - A METHODIST HOSPITAL FACILITY"         , "TX"   ,
    "METHODIST HOSPITAL NORTHEAST"       , "METHODIST TEXSAN HOSPITAL - A METHODIST HOSPITAL FACILITY"         , "TX"   ,
    "METHODIST HOSPITAL STONE OAK"       , "METHODIST TEXSAN HOSPITAL - A METHODIST HOSPITAL FACILITY"         , "TX"   ,
    "METHODIST HOSPITAL TEXSAN"          , "METHODIST TEXSAN HOSPITAL - A METHODIST HOSPITAL FACILITY"         , "TX"   ,
    "SOUTH TEXAS HOSPITAL"               , "METHODIST TEXSAN HOSPITAL - A METHODIST HOSPITAL FACILITY"         , "TX"   ,
    "METHODIST HOSPITAL"                 , "METROPOLITAN METHODIST HOSPITAL"                                   , "TX"   ,
    "METHODIST HOSPITAL METROPOLITAN"    , "METROPOLITAN METHODIST HOSPITAL"                                   , "TX"   ,
    "NORTH CENTRAL BAPTIST HOSPITAL"     , "NORTH CENTRAL BAPTIST HOSPITAL"                                    , "TX"   ,
    "NORTHEAST BAPTIST HOSPITAL"         , "NORTHEAST BAPTIST HOSPITAL"                                        , "TX"   ,
    "METHODIST HOSPITAL"                 , "NORTHEAST METHODIST HOSPITAL"                                      , "TX"   ,
    "METHODIST HOSPITAL NORTHEAST"       , "NORTHEAST METHODIST HOSPITAL"                                      , "TX"   ,
    "PAM HEALTH SPECIALTY HOSPITAL 1"    , "PAM SPECIALTY HOSPITAL OF SAN ANTONIO MEDICAL CENTER"              , "TX"   ,
    "PAM HEALTH SPECIALTY HOSPITAL 1"    , "PAM SPECIALTY HOSPITAL OF VICTORIA NORTH"                          , "TX"   ,
    "PARKLAND HOSPITAL"                  , "PARKLAND MEMORIAL HOSPITAL"                                        , "TX"   ,
    "RED RIVER HOSPITAL"                 , "RED RIVER ER AND HOSPITAL"                                         , "TX"   ,
    "ST LUKE'S BAPTIST HOSPITAL"         , "ST LUKES BAPTIST HOSPITAL"                                         , "TX"   ,
    "ST LUKE'S HEALTH - THE WOODLANDS"   , "ST LUKES THE WOODLANDS HOSPITAL"                                   , "TX"   ,
    "TEX HEALTH HUGULEY HOSP"            , "TEXAS HEALTH HUGULEY HOSPITAL"                                     , "TX"   ,
    "UNIVERSITY HOSPITAL"                , "UNIVERSITY HOSPITAL"                                               , "TX"   ,
    "VALLEY BAPTIST HOSPITAL"            , "VALLEY BAPTIST MEDICAL CENTER"                                     , "TX"   ,
    "CEDAR CREST HOSP TREAT"             , "CEDAR CREST HOSPITAL"                                              , "TX"   ,
    "GEORGETOWN BEHAVIORAL HOSPITAL"     , "GEORGETOWN BEHAVIORAL HEALTH INSTITUTE LLC"                        , "TX"   ,
    "EL PASO LTAC HOSPITAL"              , "EL PASO SPECIALTY HOSPITAL"                                        , "TX"   ,
    "PARADISE VALLEY HOSPITAL"           , "PARADISE VALLEY HOSPITAL"                                          , "CA"   ,
    "UNV CALIFORNIA SAN DIEGO HOSPITAL"  , "UC SAN DIEGO HEALTH HILLCREST - HILLCREST MED CTR"                 , "CA"   ,
    "MERCY HOSP DOWNTOWN BAKERSFIELD"    , "BAKERSFIELD MEMORIAL HOSPITAL"                                     , "CA"   ,
    "MEMORIAL HOSPITAL BAKERSFIELD"      , "BAKERSFIELD MEMORIAL HOSPITAL"                                     , "CA"   ,
    "EL CENTRO REGIONAL MED CTR"         , "EL CENTRO REGIONAL MEDICAL CENTER"                                 , "CA"   ,
    "SUTTER MED CTR SACRAMENTO"          , "SUTTER MEDICAL CENTER, SACRAMENTO"                                 , "CA"   ,
    "SUTTER MED CTR SACRAMENTO"          , "SUTTER MEDICAL CENTER - SACRAMENTO"                                , "CA"   ,
    "ARROWHEAD REGIONAL MED CENTER"      , "ARROWHEAD REGIONAL MEDICAL CENTER"                                 , "CA"   ,
    "GOOD SAMARITAN HOSPITAL"            , "GOOD SAMARITAN HOSPITAL"                                           , "CA"   ,
    "CONTRA COSTA REG MED CTR"           , "CONTRA COSTA REGIONAL MEDICAL CENTER"                              , "CA"   ,
    "KERN MEDICAL HOSPITAL"              , "KERN MEDICAL CENTER"                                               , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY MEDICAL CENTER"                              , "CA"   ,
    "ADVENTIST HEALTH BAKERSFIELD"       , "ADVENTIST HEALTH BAKERSFIELD"                                      , "CA"   ,
    "VICTOR VALLEY GLOBAL MED CENTER"    , "VICTOR VALLEY GLOBAL MEDICAL CENTER"                               , "CA"   ,
    "COSTA MESA COLLEGE HOSP"            , "COLLEGE HOSPITAL COSTA MESA"                                       , "CA"   ,
    "ADVENTIST HEALTH DELANO"            , "ADVENTIST HEALTH DELANO"                                           , "CA"   ,
    "DESERT VALLEY HOSPITAL"             , "DESERT VALLEY HOSPITAL"                                            , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY MEDICAL CENTER-MURRIETA"                     , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY MEDICAL CENTER - MURRIETA"                   , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY CHILDREN'S HOSPITAL"                         , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA VA MEDICAL CENTER"                                      , "CA"   ,
    "ALHAMBRA BHC HOSPITAL"              , "BHC ALHAMBRA HOSPITAL"                                             , "CA"   ,
    "ST JOHN'S HOSPITAL CAMARILLO"       , "ST. JOHN'S HOSPITAL CAMARILLO"                                     , "CA"   ,
    "SAN DIEGO AREA HOSPITAL"            , "UC SAN DIEGO HEALTH HILLCREST - HILLCREST MEDICAL CENTER"          , "CA"   ,
    "UNV CALIFORNIA SAN DIEGO HOSPITAL"  , "UC SAN DIEGO HEALTH HILLCREST - HILLCREST MEDICAL CENTER"          , "CA"   ,
    "PARADISE VALLEY HOSPITAL"           , "PARADISE VALLEY HOSPITAL D/P APH"                                  , "CA"   ,
    "ADVENTIST HEALTH BAKERSFIELD"       , "ENCOMPASS HEALTH REHABILITATION HOSPITAL OF BAKERSFIELD"           , "CA"   ,
    "GOOD SAMARITAN HOSPITAL"            , "GOOD SAMARITAN HOSPITAL D/P APH"                                   , "CA"   ,
    "CONTRA COSTA REG MED CTR"           , "CONTRA COSTA REGIONAL MEDICAL CENTER D/P APH"                      , "CA"   ,
    "ARROWHEAD REGIONAL MED CENTER"      , "ARROWHEAD REGIONAL MEDICAL CENTER D/P APH"                         , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY SURGICAL HOSPITAL"                           , "CA"   ,
    "LOMA LINDA UNIVERSITY MED CENTER"   , "LOMA LINDA UNIVERSITY MEDICAL"                                     , "CA"   ,
    "ADVENTIST HEALTH CASTLE"            , "ADVENTIST HEALTH CASTLE"                                           , "HI"   ,
    "HENNEPIN COUNTY MED CTR"            , "HENNEPIN COUNTY MEDICAL CENTER"                                    , "MN"   ,
    "MAYO CLINIC HEALTH SYS ALBERT LEA"  , "MAYO CLINIC HEALTH SYSTEM - ALBERT LEA AND AUSTIN"                 , "MN"   ,
    "MAYO CLINIC HEALTH SYS - MANKATO"   , "MAYO CLINIC HEALTH SYSTEM - ALBERT LEA AND AUSTIN"                 , "MN"   ,
    "ABBOTT NORTHWESTERN HOSP"           , "ABBOTT NORTHWESTERN HOSPITAL"                                      , "MN"   ,
    "M HEALTH FAIRVIEW SOUTHDALE HOSP"   , "M HEALTH FAIRVIEW SOUTHDALE HOSPITAL"                              , "MN"   ,
    "CENTRACARE RICE MEMORIAL HOSP"      , "CENTRACARE- RICE MEMORIAL HOSPITAL"                                , "MN"   ,
    "MAYO CLINIC HEALTH SYS - MANKATO"   , "MAYO CLINIC HEALTH SYSTEM - MANKATO"                               , "MN"   ,
    "MERCY HOSPITAL"                     , "MERCY HOSPITAL"                                                    , "MN"   ,
    "CENTRACARE RICE MEMORIAL HOSP"      , "CENTRACARE HEALTH SYSTEM - MELROSE HOSPITAL"                       , "MN"   ,
    "HENNEPIN COUNTY MED CTR"            , "HENNEPIN COUNTY MEDICAL CTR"                                       , "MN"   ,
    "MAYO CLINIC HEALTH SYS ALBERT LEA"  , "MAYO CLINIC ALBERT LEA AUSTIN"                                     , "MN"   ,
    "MAYO CLINIC HEALTH SYS - MANKATO"   , "MAYO CLINIC HEALTH SYS MANKATO"                                    , "MN"   ,
    "MAYO CLINIC HEALTH SYS - MANKATO"   , "MAYO CLINIC HEALTH SYS WASECA"                                     , "MN"   ,
    "MAYO CLINIC HEALTH SYS - MANKATO"   , "MAYO CLINIC HEALTH SYSTEM"                                         , "MN"   ,
    "MERCY HOSPITAL"                     , "MERCY HOSPITAL - UNITY CAMPUS"                                     , "MN"   ,
    "MEMORIAL REGIONAL HOSP."            , "MEMORIAL REGIONAL HOSPITAL"                                        , "FL"   ,
    "WEST KENDALL BAPTIST HOSP"          , "BAPTIST HOSPITAL"                                                  , "FL"   ,
    "ED FRASER MEMORIAL HOSPITAL"        , "ED FRASER MEMORIAL HOSPITAL"                                       , "FL"   ,
    "HCA FLORIDA MEMORIAL HOSPITAL"      , "HCA FLORIDA MERCY HOSPITAL"                                        , "FL"   ,
    "HCA FLORIDA MEMORIAL HOSPITAL"      , "HCA FLORIDA MEMORIAL HOSPITAL"                                     , "FL"   ,
    "LARKIN HOSPITAL"                    , "LARKIN COMMUNITY HOSPITAL"                                         , "FL"   ,
    "HCA FLORIDA KENDALL HOSPITAL"       , "HCA FLORIDA KENDALL HOSPITAL"                                      , "FL"   ,
    "WEST KENDALL BAPTIST HOSP"          , "WEST KENDALL BAPTIST HOSPITAL"                                     , "FL"   ,
    "LARKIN BEHAVIORAL HEALTH SVCS"      , "LARKIN COMMUNITY HOSPITAL BEHAVIORAL HEALTH SRVS"                  , "FL"   ,
    "JACKSON MEMORIAL HOSPITAL"          , "JACKSON MEMORIAL HOSPITAL"                                         , "FL"   ,
    "LARKIN BEHAVIORAL HEALTH SVCS"      , "LARKIN COMMUNITY HOSPITAL BEHAVIORAL HEALTH SERVICES"              , "FL"   ,
    "LARKIN HOSPITAL"                    , "LARKIN COMMUNITY HOSPITAL BEHAVIORAL HEALTH SERVICES"              , "FL"   ,
    "MEMORIAL REGIONAL HOSP."            , "MEMORIAL REGIONAL HOSPITAL SOUTH"                                  , "FL"   ,
    "MERCY HOSPITAL"                     , "MERCY HOSPITAL"                                                    , "FL"   ,
    "PALMS WEST HOSPITAL"                , "PALMS WEST HOSPITAL"                                               , "FL"   ,
    "UNIVERSITY OF MIAMI HOSPITAL"       , "UNIVERSITY OF MIAMI HOSPITAL AND CLINICS - BASCOM PALMER EYE INST" , "FL"   ,
    "UNIVERSITY OF MIAMI HOSPITAL"       , "UNIVERSITY OF MIAMI HOSPITAL AND CLINICS - UHEALTH TOWER"          , "FL"   ,
    "HOSPITAL PAVIA-SANTURCE"            , "HOSPITAL PAVIA SANTURCE"                                           , "PR"   ,
    "BAYAMON HOSPITAL"                   , "BAYAMON MEDICAL CENTER"                                            , "PR"   ,
    "HOSPITAL PAVIA-SANTURCE"            , "HOSPITAL PAVIA HATO REY, INC"                                      , "PR"   ,
    "PAVIA HOSPITAL - HATO REY"          , "HOSPITAL PAVIA HATO REY, INC"                                      , "PR"   ,
    "BRONSON METHODIST HOSPITAL"         , "BRONSON METHODIST HOSPITAL"                                        , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD HEALTH HOSPITAL"                                        , "MI"   ,
    "BRONSON BATTLE CREEK HOSP"          , "BRONSON BATTLE CREEK HOSPITAL"                                     , "MI"   ,
    "MUNSON HEALTHCARE CADILLAC HOSP"    , "MUNSON HEALTHCARE CADILLAC HOSPITAL"                               , "MI"   ,
    "PROMEDICA MONROE REG HOSP"          , "PROMEDICA MONROE REGIONAL HOSPITAL"                                , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD HEALTH ST JOHN HOSPITAL"                                , "MI"   ,
    "MCLAREN PORT HURON HOSP"            , "MCLAREN PORT HURON"                                                , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD HEALTH WEST BLOOMFIELD HOSPITAL"                        , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD HOSPITAL"                                               , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD WYANDOTTE HOSPITAL"                                     , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD WEST BLOOMFIELD HOSPITAL"                               , "MI"   ,
    "BRONSON BATTLE CREEK HOSP"          , "BRONSON BATTLE CREEK HOSPITAL - FIELDSTONE CENTER"                 , "MI"   ,
    "BRONSON HOSPITAL FIELDSTONE CENTER" , "BRONSON BATTLE CREEK HOSPITAL - FIELDSTONE CENTER"                 , "MI"   ,
    "HENRY FORD HOSPITAL"                , "HENRY FORD HEALTH WYANDOTTE HOSPITAL"                              , "MI"   ,
    "BRONXCARE HEALTH SYSTEM"            , "BRONXCARE HOSPITAL CENTER"                                         , "NY"   ,
    "Jamaica Hospital Med Ctr"           , "JAMAICA HOSPITAL MEDICAL CENTER"                                   , "NY"   ,
    "NASSAU UNIV MED CTR"                , "NASSAU UNIVERSITY MEDICAL CENTER"                                  , "NY"   ,
    "UNITED MEMORIAL MED CTR"            , "UNITED MEMORIAL MEDICAL CENTER"                                    , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK-PRESBYTERIAN HOSPITAL"                                    , "NY"   ,
    "KENMORE MERCY HOSPITAL"             , "KENMORE MERCY HOSPITAL"                                            , "NY"   ,
    "ROCHESTER GENERAL HOSPITAL"         , "ROCHESTER GENERAL HOSPITAL"                                        , "NY"   ,
    "KINGS COUNTY HOSPITAL"              , "KINGS COUNTY HOSPITAL CENTER"                                      , "NY"   ,
    "UNITY HOSPITAL"                     , "UNITY HOSPITAL"                                                    , "NY"   ,
    "BUFFALO GENERAL HOSPITAL"           , "MERCY HOSPITAL OF BUFFALO"                                         , "NY"   ,
    "STRONG MEMORIAL HOSPITAL"           , "STRONG MEMORIAL HOSPITAL"                                          , "NY"   ,
    "BUFFALO GENERAL HOSPITAL"           , "BUFFALO GENERAL MEDICAL CENTER"                                    , "NY"   ,
    "UNITED MEMORIAL MED CTR"            , "UNITED MEMORIAL MEDICAL CENTER NORTH STREET CAMPUS"                , "NY"   ,
    "UNITED MEMORIAL MED CTR"            , "UNITED MEMORIAL MEDICAL CENTER BANK STREET CAMPUS"                 , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK - PRESBYTERIAN BROOKLYN METHODIST HOSPITAL"               , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK - PRESBYTERIAN - LOWER MANHATTAN HOSPITAL"                , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK - PRESBYTERIAN HOSPITAL - NEW YORK WEILL CORNELL CENTER"  , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK - PRESBYTERIAN HOSPITAL - COLUMBIA PRESBYTERIAN CENTER"   , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK - PRESBYTERIAN HOSPITAL - ALLEN HOSPITAL"                 , "NY"   ,
    "NEW YORK PRESBYTERIAN HOSPITAL"     , "NEW YORK PRESBYTERIAN MORGAN STANLEY CHILDREN'S HOSPITAL"          , "NY"   ,
    "LOCKPORT MEMORIAL HOSPITAL"         , "LOCKPORT MEMORIAL HOSPITAL, A CAMPUS OF MOUNT ST MARY'S"           , "NY"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS HOSPITAL PLYMOUTH"                           , "MA"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS HOSPITAL - PLYMOUTH"                         , "MA"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS MEDICAL CENTER"                              , "MA"   ,
    "SOUTH SHORE HOSPITAL"               , "SOUTH SHORE HOSPITAL"                                              , "MA"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS HOSPITAL - MILTON"                           , "MA"   ,
    "LAHEY HOSPITAL & MED CTR"           , "LAHEY HOSPITAL & MEDICAL CENTER, BURLINGTON"                       , "MA"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS HOSPITAL - MILTON INC"                       , "MA"   ,
    "BETH ISRAEL DEACONESS HOSP"         , "BETH ISRAEL DEACONESS MED CTR - WEST"                              , "MA"   ,
    "LAHEY HOSPITAL & MED CTR"           , "LAHEY HOSPITAL AND MEDICAL CENTER - BURLINGTON"                    , "MA"   ,
    "LEMUEL SHATTUCK HOSPITAL"           , "LEMUEL SHATTUCK HOSPITAL"                                          , "MA"   ,
    "ST MARY'S HOSPITAL"                 , "ST. MARY'S HOSPITAL"                                               , "AZ"   ,
    "ST. JOSEPH'S HOSPITAL & MED. CEN."  , "ST JOSEPH'S HOSPITAL"                                              , "AZ"   ,
    "YUMA REGIONAL MED CTR"              , "YUMA REGIONAL MEDICAL CENTER"                                      , "AZ"   ,
    "VALLEYWISE HEALTH MED CTR"          , "VALLEYWISE HEALTH MEDICAL CENTER"                                  , "AZ"   ,
    "ST. JOSEPH'S HOSPITAL & MED. CEN."  , "ST JOSEPHS HOSPITAL AND MEDICAL CENTER"                            , "AZ"   ,
    "CHANDLER REG MED CTR"               , "CHANDLER REGIONAL MEDICAL CENTER"                                  , "AZ"   ,
    "BANNER IRONWOOD MED CTR"            , "BANNER IRONWOOD MEDICAL CENTER"                                    , "AZ"   ,
    "LA PAZ REGIONAL HOSPITAL"           , "LA PAZ REGIONAL HOSPITAL"                                          , "AZ"   ,
    "FLORENCE HOSPITAL"                  , "FLORENCE HOSPITAL"                                                 , "AZ"   ,
    "MOUNTAIN VISTA MED CTR"             , "MOUNTAIN VISTA MEDICAL CENTER, LP"                                 , "AZ"   ,
    "ST. JOSEPH'S HOSPITAL & MED. CEN."  , "ST JOSEPH'S WESTGATE MEDICAL CENTER"                               , "AZ"   ,
    "ST. JOSEPH'S HOSPITAL & MED. CEN."  , "ST. JOSEPH'S HOSPITAL AND MEDICAL CENTER"                          , "AZ"   ,
    "ST. JOSEPH'S HOSPITAL & MED. CEN."  , "ST JOSEPH'S HOSPITAL AND MEDICAL CENTER"                           , "AZ"   ,
    "INTEGRIS HEALTH PONCA CITY HOSPITA" , "INTEGRIS HEALTH PONCA CITY"                                        , "OK"   ,
    "INTEGRIS HEALTH BAPTIST MEDICAL"    , "INTEGRIS BAPTIST MEDICAL CENTER, INC"                              , "OK"   ,
    "ST ELIZABETH YOUNGSTOWN HOSPITAL"   , "ST ELIZABETH YOUNGSTOWN HOSPITAL"                                  , "OH"   ,
    "MERCY HEALTH - TIFFIN HOSPITAL"     , "MERCY HEALTH - TIFFIN HOSPITAL"                                    , "OH"   ,
    "MERCY HEALTH - TIFFIN HOSPITAL"     , "MERCY HEALTH TIFFIN HOSPITAL"                                      , "OH"   ,
    "BELLMONT PINES HOSPITAL"            , "BELMONT PINES HOSPITAL"                                            , "OH"   ,
    "UNIV HOSP GEAUGA MED CTR"           , "UHHS - GEAUGA REGIONAL HOSPITAL"                                   , "OH"   ,
    "ST ELIZABETH YOUNGSTOWN HOSPITAL"   , "MERCY HEALTH ST. ELIZABETH YOUNGSTOWN HOSPITAL"                    , "OH"   ,
    "ST ELIZABETH YOUNGSTOWN HOSPITAL"   , "MERCY HEALTH ST. ELIZABETH BOARDMAN HOSPITAL"                      , "OH"   ,
    "BARTLETT REGIONAL HOSPITAL"         , "BARTLETT REGIONAL HOSPITAL"                                        , "AK"   ,
    "HOLY CROSS HOSPITAL"                , "HOLY CROSS HOSPITAL"                                               , "IL"   ,
    "COOK COUNTY HOSPITAL-PROVIDENT"     , "PROVIDENT HOSPITAL OF CHICAGO"                                     , "IL"   ,
    "RIVEREDGE HOSPITAL"                 , "AERIES HEALTHCARE OF ILLINOIS, INC., DBA RIVEREDGE HOSPITAL"       , "IL"   ,
    "COOK COUNTY HOSPITAL-PROVIDENT"     , "PROVIDENT HOSPITAL OF COOK COUNTY"                                 , "IL"   ,
    "RIVEREDGE HOSPITAL"                 , "RIVEREDGE HOSPITAL INC"                                            , "IL"   ,
    "UCHICAGO MEDICINE HOSPITAL CHICAGO" , "UNIVERSITY OF ILLINOIS HOSPITAL AT CHICAGO"                        , "IL"   ,
    "UCHICAGO MEDICINE HOSPITAL CHICAGO" , "UCHICAGO MEDICINE"                                                 , "IL"   ,
    "CENTRA HEALTH"                      , "CENTRA HEALTH -  LYNCHBURG GEN HOSPITAL"                           , "VA"   ,
    "MARY WASHINGTON HOSPITAL"           , "MARY WASHINGTON HOSPITAL"                                          , "VA"   ,
    "JOHNSTON MEMORIAL HOSPITAL"         , "JOHNSTON MEMORIAL HOSPITAL"                                        , "VA"   ,
    "VCU HEALTH TAPPAHANNOCK HOSPITAL"   , "VCU HEALTH TAPPAHANNOCK HOSPITAL"                                  , "VA"   ,
    "SENTARA CAREPLEX HOSPITAL"          , "SENTARA CAREPLEX HOSPITAL"                                         , "VA"   ,
    "SPOTSYLVANIA REG MED CTR"           , "SPOTSYLVANIA REGIONAL MEDICAL CENTER"                              , "VA"   ,
    "CENTRA HEALTH"                      , "CENTRA HEALTH"                                                     , "VA"   ,
    "CENTRA SOUTHSIDE COMM HOSP"         , "CENTRA SOUTHSIDE COMMUNITY HOSPITAL"                               , "VA"   ,
    "CHIPPENHAM HOSPITAL - RICHMOND"     , "CHIPPENHAM HOSPITAL"                                               , "VA"   ,
    "CHI HEALTH MERCY COUNCIL BLUFFS"    , "CHI HEALTH MERCY COUNCIL BLUFFS"                                   , "IA"   ,
    "MERCY MED CTR CEDAR RAPID"          , "MERCY MEDICAL CENTER - CEDAR RAPIDS"                               , "IA"   ,
    "CIBOLA GENERAL HOSPITAL"            , "CIBOLA GENERAL HOSPITAL"                                           , "NM"   ,
    "TACOMA GENERAL HOSPITAL"            , "TACOMA GENERAL ALLENMORE HOSPITAL"                                 , "WA"   ,
    "TACOMA GENERAL HOSPITAL"            , "MULTICARE TACOMA GENERAL HOSPITAL"                                 , "WA"   ,
    "SAINT JOSEPH HOSPITAL"              , "SAINT JOSEPH HOSPITAL"                                             , "CO"   ,
    "COLORADO MENTAL HEALTH INSTITUTE"   , "COLORADO MENTAL HEALTH HOSPITAL IN PUEBLO"                         , "CO"   ,
    "COLORADO MENTAL HEALTH INSTITUTE"   , "COLORADO MENTAL HEALTH HOSPITAL IN FORT LOGAN"                     , "CO"   ,
    "HIGHLANDS BEHAVIORAL HEALTH"        , "HIGHLANDS BEHAVIORAL HEALTH SYSTEM"                                , "CO"   ,
    "COLORADO MENTAL HEALTH INSTITUTE"   , "COLORADO MENTAL HEALTH INSTITUTE AT FT LOGAN"                      , "CO"   ,
    "COLORADO MENTAL HEALTH INSTITUTE"   , "COLORADO MENTAL HEALTH INSTITUTE AT PUEBLO - PSYCH"                , "CO"   ,
    "DENVER HEALTH MEDICAL CENTER"       , "DENVER HEALTH MEDICAL CENTER"                                      , "CO"   ,
    "SAINT JOSEPH HOSPITAL"              , "CHILDREN'S HOSPITAL COLORADO AT ST JOSEPHS HOSP"                   , "CO"   ,
    "MERCY HOSPITAL SOUTH"               , "MERCY HOSPITAL ST LOUIS"                                           , "MO"   ,
    "MERCY HOSPITAL SOUTH"               , "MERCY HOSPITAL ST. LOUIS"                                          , "MO"   ,
    "MERCY HOSPITAL SOUTH"               , "MERCY HOSPITAL SOUTH"                                              , "MO"   ,
    "MERCY HOSPITAL SOUTH"               , "MERCY HOSPITAL SOUTHEAST"                                          , "MO"   ,
    "NORTHERN NEVADA MED CTR"            , "NORTHERN NEVADA MEDICAL CENTER"                                    , "NV"   ,
    "SUMMERLIN HOSPITAL MEDICAL CENTER"  , "SUMMERLIN HOSPITAL MEDICAL CENTER"                                 , "NV"   ,
    "HENDERSON HOSPITAL"                 , "HENDERSON HOSPITAL"                                                , "NV"   ,
    "HENDERSON HOSPITAL"                 , "WEST HENDERSON HOSPITAL"                                           , "NV"   ,
    "DESERT VIEW HOSPITAL"               , "DESERT VIEW HOSPITAL"                                              , "NV"   ,
    "HENDERSON HOSPITAL"                 , "ENCOMPASS HEALTH REHABILITATION HOSPITAL OF HENDERSON"             , "NV"   ,
    "NORTHERN NEVADA MED CTR"            , "NORTHERN NEVADA SIERRA MEDICAL CENTER"                             , "NV"   ,
    "UNION HOSPITAL"                     , "UNION HOSPITAL INC"                                                , "IN"   ,
    "ESKENAZI HEALTH"                    , "ESKENAZI HEALTH"                                                   , "IN"   ,
    "UNION HOSPITAL"                     , "UNION HOSPITAL CLINTON"                                            , "IN"   ,
    "PARKVIEW HOSPITAL RANDALLIA"        , "PARKVIEW HOSPITAL RANDALLIA"                                       , "IN"   ,
    "PHOEBE PUTNEY MEMORIAL HOSP"        , "PHOEBE PUTNEY MEMORIAL HOSPITAL"                                   , "GA"   ,
    "PHOEBE SUMTER MED CTR"              , "PHOEBE SUMTER MEDICAL CENTER"                                      , "GA"   ,
    "GRADY MEMORIAL HOSPITAL"            , "GRADY MEMORIAL HOSPITAL"                                           , "GA"   ,
    "ST FRANCIS HOSPITAL"                , "ST FRANCIS HOSPITAL- EMORY HEALTHCARE"                             , "GA"   ,
    "ST FRANCIS HOSPITAL"                , "ST FRANCIS HOSPITAL - EMORY HEALTHCARE"                            , "GA"   ,
    "GUAM MEMORIAL HOSPITAL"             , "GUAM MEMORIAL  HOSPITAL AUTHORITY"                                 , "GU"   ,
    "GUAM MEMORIAL HOSPITAL"             , "GUAM MEMORIAL HOSPITAL AUTHORITY"                                  , "GU"   ,
    "HACKENSACK MED CTR"                 , "HACKENSACK UNIVERSITY MEDICAL CENTER"                              , "NJ"   ,
    "TRINITAS REGIONAL MED CTR"          , "TRINITAS REGIONAL MEDICAL CENTER"                                  , "NJ"   ,
    "HACKENSACK MED CTR"                 , "CAREPOINT HEALTH-HOBOKEN UNIVERSITY MEDICAL CENTER"                , "NJ"   ,
    "HACKENSACK MED CTR"                 , "CAREPOINT HEALTH - HOBOKEN UNIVERSITY MEDICAL CENTER"              , "NJ"   ,
    "JERSEY CITY MED CTR"                , "JERSEY CITY MEDICAL CENTER"                                        , "NJ"   ,
    "UNIVERSITY HOSPITAL"                , "THE UNIVERSITY HOSPITAL"                                           , "NJ"   ,
    "TRINITAS REGIONAL MED CTR"          , "CARE ONE AT TRINITAS REGIONAL MEDICAL CENTER"                      , "NJ"   ,
    "HACKENSACK MED CTR"                 , "HACKENSACKMERIDIAN HEALTH, MOUNTAINSIDE MEDICAL CENTER"            , "NJ"   ,
    "HACKENSACK MED CTR"                 , "PASCACK VALLEY MEDICAL CENTER, HACKENSACK MERIDIAN HEALTH"         , "NJ"   ,
    "UNIVERSITY HOSPITAL"                , "UNIVERSITY HOSPITAL"                                               , "NJ"   ,
    "RHODE ISLAND HOSPITAL"              , "RHODE ISLAND HOSPITAL"                                             , "RI"   ,
    "MIRIAM HOSPITAL"                    , "THE MIRIAM HOSPITAL"                                               , "RI"   ,
    "RHODE ISLAND HOSPITAL"              , "MEMORIAL HOSPITAL OF RHODE ISLAND"                                 , "RI"   ,
    "RHODE ISLAND HOSPITAL"              , "REHABILITATION HOSPITAL OF RHODE ISLAND"                           , "RI"   ,
    "READING HOSPITAL"                   , "READING HOSPITAL"                                                  , "PA"   ,
    "LEHIGH VALLEY HOSPITAL - POCONO"    , "LEHIGH VALLEY HOSPITAL"                                            , "PA"   ,
    "UPMC PRESBYTERIAN HOSPITAL"         , "UPMC PRESBYTERIAN SHADYSIDE"                                       , "PA"   ,
    "LEHIGH VALLEY HOSPITAL - POCONO"    , "LEHIGH VALLEY HOSPITAL - POCONO"                                   , "PA"   ,
    "UPMC PRESBYTERIAN HOSPITAL"         , "UPMC PRESBYTERIAN SHADYSIDE - TRANSPLANT CENTER"                   , "PA"   ,
    "OSAWATAMIE STATE HOSPITAL"          , "OSAWATOMIE STATE HOSPITAL"                                         , "KS"   ,
    "CHI HEALTH MIDLANDS HOSPITAL"       , "CHI HEALTH MIDLANDS"                                               , "NE"   ,
    "WENTWORTH DOUGLAS HOSPITAL"         , "WENTWORTH-DOUGLASS HOSPITAL"                                       , "NH"   ,
    "WENTWORTH DOUGLAS HOSPITAL"         , "WENTWORTH - DOUGLASS HOSPITAL"                                     , "NH"
  )
